package assets {
  import flash.display.Bitmap;
  import flash.display.BitmapData;
  import mx.core.FlexGlobals;

  /**
   * Class that allows accessing bundled assets.
   *
   * This class is autogenerated by 'flex:assets:build' rake task.
   */
  public class AssetsBundle {
    private static var gameModules : Array = [
%game_modules%
    ];
    private static var battleModules : Array = [
%battle_modules%
    ];

    public static function getGameModules() : Array
    {
      return gameModules;
    }

    public static function getBattleModules() : Array
    {
      return battleModules;
    }
  }
}