package assets {
  import mx.modules.ModuleBase;
  /**
   * Class for bundled assets configuration items.
   *
   * This class is autogenerated by 'flex:assets:build' rake task.
   */
  public class AssetsConfig extends ModuleBase {
    public var config : Object = %config%;
  }
}