package assets {
  import mx.modules.ModuleBase;
  /**
   * Class for bundled assets configuration items.
   *
   * This class is autogenerated by 'flex:assets:build' rake task.
   */
  public class AssetsConfig extends ModuleBase {
    // This is fucking ridiculous. Avast heuristics suck - if .swf has small
    // size and contains no images it will be flaged as virus. FML.
    [Embed(source="../../../assets/avastSucks.png", mimeType="application/octet-stream")]
    private var avastSucks:Class;

    public var config : Object = %config%;
  }
}