package assets {
  import flash.display.Bitmap;
  import flash.display.BitmapData;
  import mx.core.FlexGlobals;

  /**
   * Class that allows accessing bundled assets.
   *
   * This class is autogenerated by 'flex:assets:build' rake task.
   */
  public class AssetsBundle {
    private static var modules : Array = [
%modules%
    ];

    public static function getModules() : Array
    {
      return modules;
    }
  }
}