package assets {
  import mx.modules.ModuleBase;

  /**
   * Class that bundles assets.
   *
   * This class is autogenerated by 'flex:assets:build' rake task.
   */
  public class %bundle_name% extends ModuleBase
  {

    // Variables with embedded assets
%asset_variables%

    // Hash for resolving name -> asset.
    private var assetsHash: Object = {
%asset_mappings%
    };

    /**
     * Returns a hash which maps SWFs names to actual byte array classes.
     */
    public function getAssetsHash() : Object
    {
      return assetsHash;
    }
  }
}