package assets {
  import mx.modules.ModuleBase;

  /**
   * Class that bundles assets.
   *
   * This class is autogenerated by 'flex:assets:build' rake task.
   */
  public class %bundle_name% extends ModuleBase
  {

    // Variables with embedded images
%image_variables%

    // Hash for resolving name -> image.
    private var images: Object = {
%image_mappings%
    };

    /**
     * Returns a hash which maps SWFs names to actual byte array classes.
     */
    public function getSWFsHash() : Object
    {
      return images;
    }
  }
}