---
production:
  adapter: mysql
  host: localhost
  database: spacegame
  username: root
  password: jhothe
development:
  adapter: mysql
  host: localhost
  database: spacegame
  username: root
  password: jhothe
test:
  adapter: mysql
  host: localhost
  database: spacegame_test
  username: root
  password: jhothe
