---
production:
  adapter: mysql
  host: localhost
  database: spacegame
  username: spacegame
  password: Hzbm6nsdcqBn2uBd
development:
  adapter: mysql
  host: localhost
  database: spacegame
  username: spacegame
  password: Hzbm6nsdcqBn2uBd
