require 'rubygems'
require 'rake'
require 'rake/clean'
require 'rubygems/package_task'
require 'rdoc/task'
require 'rake/testtask'

Rake::RDocTask.new do |rdoc|
  files =['README', 'LICENSE', 'lib/**/*.rb']
  rdoc.rdoc_files.add(files)
  rdoc.main = "README" # page to start on
  rdoc.title = "space_server Docs"
  rdoc.rdoc_dir = 'doc/rdoc' # rdoc output folder
  rdoc.options << '--line-numbers'
end

class TemplatesBuilder
  TEMPLATE_DIR = File.join(File.dirname(__FILE__), 'tasks', 'templates')

  def self.read_template(name, params={})
    content = File.read(File.join(TEMPLATE_DIR, name))
    params.each do |key, value|
      content.gsub!(key, value)
    end

    content
  end
end

task :environment do
  require File.expand_path(File.dirname(__FILE__) + "/lib/initializer.rb")
end

# Load tasks located in tasks/*.rake
Dir.glob(File.dirname(__FILE__) + "/tasks/*.rake").each { |file| load file }
