package components.base.viewport
{
   import flash.geom.Rectangle;

   /**
    * A client of <code>VisibleAreaTracker</code> that knows what to do with results generated by the tracker.
    */
   public interface IVisibleAreaTrackerClient
   {
      /**
       * Called when some area of a content of a viewport has become <b>visible</b>.
       * 
       * @param area <code>Rectangle</code> defining the area.
       * <ul><b>
       *    <li>Not null.</li>
       * </b></ul>
       * Here:
       * <ul>
       *    <li><code>area.x</code> - X coordinate (pixel) of the area in content coordinate space;</li>
       *    <li><code>area.y</code> - Y coordinate (pixel) of the area in content coordinate space;</li>
       *    <li><code>area.width</code> - width (in pixels) of the area</li>
       *    <li><code>area.height</code> - height (in pixels) of the area</li>
       * </ul>
       */
      function areaShown(area:Rectangle) : void;
      
      /**
       * Called when come area of a content of a viewport has become <b>invisible</b>.
       * 
       * @param area <code>Rectangle</code> defining the area.
       * <ul><b>
       *    <li>Not null.</li>
       * </b></ul>
       * Here:
       * <ul>
       *    <li><code>area.x</code> - X coordinate (pixel) of the area in content coordinate space;</li>
       *    <li><code>area.y</code> - Y coordinate (pixel) of the area in content coordinate space;</li>
       *    <li><code>area.width</code> - width (in pixels) of the area</li>
       *    <li><code>area.height</code> - height (in pixels) of the area</li>
       * </ul>
       */
      function areaHidden(area:Rectangle) : void;
   }
}