package components.base.viewport
{
   import flash.geom.Rectangle;

   /**
    * A client of <code>VisibleAreaTracker</code> that knows what to do with results generated by the tracker.
    */
   public interface IVisibleAreaTrackerClient
   {
      /**
       * Called whenever visible area of a content of a viewport changes.
       * 
       * @param newVisibleArea new visible area after the change. If no area is visible,
       *                       this will be instance of <code>Rectangle</code> which has either
       *                       <code>width</code> or <code>height</code> properties equal to 0
       * <ul><b>
       *    <li>not null</li>
       * </b></ul>
       * 
       * @param areasHidden array of areas that became invisible after change. Has at most 4 elements and
       *                    may not have any elements.
       * <ul><b>
       *    <li>not null</li>
       * </b></ul>
       * 
       * @param areasShown array of hidden areas after change. Has at most 4 elements and
       *                   may not have any elements.
       * <ul><b>
       *    <li>not null</li>
       * </b></ul>
       */
      function visibleAreaChange(visibleArea:Rectangle,
                                 areasHidden:Vector.<Rectangle>,
                                 areasShown:Vector.<Rectangle>) : void;
   }
}