require 'rubygems'
require 'rake'
require 'fileutils'
require 'digest/sha1'
require 'socket'
require 'yaml'

basedir = File.dirname(__FILE__)
load basedir + '/../server/Rakefile'
Dir[basedir + '/tasks/*.rb'].each(&method(:require))

namespace :build do
  # Required flash version
  FLASH_VERSION = "10.2.0"
  # Name of output swf file (without .swf!)
  swf_name = "SpaceGame"

  # Values used in tasks.
  FLEX_HOME = ENV["FLEX_HOME"] or raise(
    "FLEX_HOME environment variable is not set!"
  )
  as3_st = "#{basedir}/vendor/as3_st.jar"
  FCSH = File.join(FLEX_HOME, "bin", Rake::Win32.windows? ? "fcsh.exe" : "fcsh")
  FCSHD_PORT = "53000"
  FCSHD = "#{basedir}/vendor/FlexShellScript.jar"
  src_dir = "#{basedir}/src"
  src_pp_dir = "#{basedir}/src-pp"
  html_extras_dir = "#{basedir}/html-extras"
  html_files = %W{
    #{src_dir}/index.template.html
    #{src_dir}/game.js
    #{html_extras_dir}/jquery-1.6.4.min.js
    #{html_extras_dir}/swfobject-2.2.js
    #{html_extras_dir}/favicon.ico
    #{html_extras_dir}/playerProductInstall.swf
    #{html_extras_dir}/images
  }
  locale_dir = "#{src_dir}/locale"
  assets_dir = File.expand_path("#{basedir}/../assets")
  raw_assets_dir = "#{assets_dir}/data"
  bundles_yml = "#{raw_assets_dir}/bundles.yml"
  anti_avast = "#{raw_assets_dir}/avastSucks.png"
  assets_config_dir = "#{assets_dir}/current/config"
  prepared_assets_dir = "#{assets_dir}/current/bundled-prepared"
  compiled_assets_dir = "#{assets_dir}/current/bundled-compiled"
  src_assets_dir = "#{src_dir}/assets"
  lib_dir = "#{basedir}/libs"
  output_dir = "#{basedir}/target"
  bin_dir = "#{output_dir}/bin"
  bin_swf = "#{bin_dir}/#{swf_name}.swf"
  bin_version = "#{bin_dir}/VERSION"
  test_report_dir = "#{output_dir}/report"
  dist_dir = "#{output_dir}/dist"
  dist_locale_dir = "#{dist_dir}/locale"
  dist_assets_dir = "#{dist_dir}/assets"

  def info(message)
    format = "%Y-%m-%d %H:%M:%S"
    now = Time.now
    puts "[%s] %s" % [now.strftime(format), message]
    if block_given?
      yield
      end_time = Time.now
      time_taken = end_time - now
      puts "[%s] Done. (took %3.1fs)" % [
        end_time.strftime(format), time_taken
      ]
    end
  end

  def fcsh_running?
    socket = TCPSocket.open("127.0.0.1", FCSHD_PORT)
    socket.close
    true
  rescue Errno::ECONNREFUSED
    false
  rescue Exception => e
    puts e.class
    raise e
  end

  def fcsh(*args)
    puts fcsh_running?
    unless fcsh_running?
      puts
      puts "  ERROR: fcsh is not running, please launch it with"
      puts "         `rake build:fcsh` or use fcsh=0 env var to "
      puts "         disable fcsh!"
      puts
      exit
    end

    if args.find { |a| a.include?(" ") }
      puts
      puts "  ERROR: Cannot use this from a directory that contains spaces!"
      puts "         FCSH does not support it!"
      puts
      exit
    end

    fcsh_cmd = args.join(" ")
    info "Running %s" % fcsh_cmd
    fcsh_run("client", fcsh_cmd)
  end

  def fcsh_run(*args)
    run("java", "-jar", FCSHD, *args)
  end

  # Compiles _source_mxml_ to _output_swf_.
  def mxmlc(source_mxml, output_swf, options={})
    args = []

    add_args = Proc.new do |name, flag, block|
      if options[name] && options[name].size > 0
        if flag.nil?
          options[name].each do |item|
            item = block.nil? ? item : block.call(item)
            args.push item
          end
        else
          args.push("#{flag}+=" +
            options[name].map { |item| block.nil? ? item : block.call(item) }.
              join(",")
          )
        end
      end
    end

    # Construct args array.
    add_args.call :libraries, "-compiler.library-path",
                  lambda { |path| File.expand_path(path) }
    add_args.call :keep_metadata, "-compiler.keep-as3-metadata"
    add_args.call :compiler_flags, nil,
                  lambda { |flag| "-compiler.#{flag}" }
    add_args.call :flags

    args.unshift "mxmlc"
    args += %W{-output #{File.expand_path(output_swf)}
      #{File.expand_path(source_mxml)}}

    if ENV['fcsh'] == "0"
      cmd = args.map(&:inspect).join(" ")
      info "Running %s" % cmd
      run(*cmd)
    else
      fcsh(*args)
    end
  end

  # Calculates and returns SHA1 checksum of file contents.
  def checksum(file)
    digest = Digest::SHA1.new
    digest.hexdigest(File.read(file))
  end

  # Return file name with checksum appended before extension.
  def append_checksum(file_name, checksum)
    file_name.sub(/\.(\w+)$/, "-#{checksum}.\\1")
  end

  def remove_glob(path)
    info "Removing: #{path}"
    files = Dir[path]
    FileUtils.rm_r files unless files.blank?
  end

  # Copies all files matched by glob. #copy is taken by Rake method.
  def copy_glob(base_dir, glob, destination)
    FileUtils.mkdir_p destination
    Dir[File.join(base_dir, glob)].each do |path|
      info "Copying #{path}"
      basename = path.sub(/^#{base_dir}#{File::SEPARATOR}?/, '')

      target = "#{destination}/#{basename}"
      FileUtils.mkdir_p File.dirname(target)
      FileUtils.cp path, target
    end
  end

  # Copies all files matched by glob, and writes their new names into
  # destination/checksums
  def copy_and_checksum(base_dir, glob, destination)
    checksums = ""
    FileUtils.mkdir_p destination
    Dir[File.join(base_dir, glob)].each do |path|
      info "Checksumming and copying #{path}"
      checksum = checksum(path)
      basename = path.sub(/^#{base_dir}#{File::SEPARATOR}?/, '')
      checksummed_name = append_checksum(basename, checksum)

      target = "#{destination}/#{checksummed_name}"
      FileUtils.mkdir_p File.dirname(target)
      FileUtils.cp path, target
      checksums += "#{basename} #{checksummed_name}\n"
    end
    File.open("#{destination}/checksums", "wb") { |f| f.write checksums }
  end

  namespace :clean do
    desc "Remove all generated asset files."
    task :assets do
      [
        "#{compiled_assets_dir}/*.swf", "#{compiled_assets_dir}/assets/*.as",
        "#{assets_config_dir}/*.yml", "#{prepared_assets_dir}/*"
      ].each do |path|
        remove_glob(path)
      end
    end

    desc "Remove all generated swf files."
    task :swf do
      remove_glob(output_dir)
    end
  end

  desc "Remove all files created during the build process."
  task :clean => ["build:clean:assets", "build:clean:swf"]

  namespace :prepare do
    desc "Checks locales for validity."
    task :locales do
      checker = Tasks::LocaleChecker.new(locale_dir)
      checker.check
      checker.report
    end

    desc "Compile raw assets into SWFs."
    task :assets do
      info "Preparing assets" do
        processor = Tasks::Assets::Processor.new(
          "#{raw_assets_dir}/bundled", prepared_assets_dir, assets_config_dir,
          ENV['debug'] == "1"
        )
        processor.invoke
      end
    end

    desc "Generate files needed for bundle compilation."
    task :bundles do
      bundler = Tasks::Assets::Bundler.from_yaml(bundles_yml)
      info "Generating AssetsBundle.as" do
        File.open(File.join(src_dir, 'assets', 'AssetsBundle.as'), 'w') do |f|
          f.write bundler.assets_bundle
        end
      end
      info "Generating AssetsConfig.as" do
        bundler.generate_assets_config(
          anti_avast, assets_config_dir, compiled_assets_dir
        )
      end
      info "Generating bundle .as files" do
        bundler.generate_bundle_files(prepared_assets_dir, compiled_assets_dir)
      end
    end
  end

  prepare_deps = [
    "build:prepare:locales", "build:prepare:assets", "build:prepare:bundles"
  ]
  desc "Run all tasks in prepare namespace."
  task :prepare => prepare_deps

  desc "Launches FCSH daemon."
  task :fcsh do
    if fcsh_running?
      puts "FCSHD is already running."
      return
    end

    puts "Launching FCSHD..."
    fcsh_run("server", FCSH, FCSHD_PORT)
  end

  desc "Compile for IntelliJ IDEA"
  task :idea => ["build:compile:swf", "build:copy"]

  namespace :compile do
    desc "Compile assets into SWF files"
    task :assets do
      info "Compiling assets" do
        bundler = Tasks::Assets::Bundler.from_yaml(bundles_yml)
        bundler.compile(compiled_assets_dir)
      end
    end

    desc "Preprocess source with stacktracer."
    task :preprocess do
      info "Preprocessing with stacktracer" do
        run "java", "-jar", as3_st, src_dir, src_pp_dir
      end
    end

    desc "Compile SpaceGame into SWF file. Pass debug=1 for debug build."
    task :swf do
      [output_dir, bin_dir, dist_dir].each do |dir|
        info "Creating #{dir}."
        FileUtils.mkdir_p dir
      end

      Rake::Task['build:compile:preprocess'].invoke

      info "Compiling SpaceGame..." do
        compiler_flags = %w{
          as3 strict incremental optimize
          verbose-stacktraces
          headless-server report-invalid-styles-as-warnings
          show-actionscript-warnings
          show-invalid-css-property-warnings show-unused-type-selector-warnings
          warn-array-tostring-changes warn-assignment-within-conditional
          warn-bad-array-cast warn-bad-bool-assignment warn-bad-date-cast
          warn-bad-es3-type-method warn-bad-es3-type-prop
          warn-bad-nan-comparison
          warn-bad-null-assignment warn-bad-null-comparison
          warn-bad-undefined-comparison warn-boolean-constructor-with-no-args
          warn-changes-in-resolve warn-class-is-sealed
          warn-const-not-initialized
          warn-constructor-returns-value warn-deprecated-event-handler-error
          warn-deprecated-function-error warn-deprecated-property-error
          warn-duplicate-argument-names warn-duplicate-variable-def
          warn-instance-of-changes warn-internal-error warn-level-not-supported
          warn-missing-namespace-decl warn-negative-uint-literal
          warn-no-type-decl
          warn-number-from-string-changes warn-slow-text-field-addition
          warn-unlikely-function-value
        }
        compiler_flags.push "debug" unless ENV['no_debug'] || ENV['NO_DEBUG']

        build = Time.now.strftime("%Y-%m%d-%H%M")
        version_file = "#{src_pp_dir}/application/Version.as"
        old_version = nil
        begin
          File.modify(version_file) do |contents|
            old_version = contents.match(/VERSION: String = "(.*?)"/)
            if old_version.nil?
              puts "Cannot find old version in #{version_file}!"
              exit
            end
            old_version = old_version[1]
            contents.sub(
              %Q{VERSION: String = "#{old_version}"},
              %Q{VERSION: String = "#{build}"} 
            )
          end
          
          File.open(bin_version, "w") { |f| f.write(build + "\n") }

          mxmlc(
            "#{src_pp_dir}/SpaceGame.mxml",
            bin_swf,
            :libraries => Dir["#{lib_dir}/*.swc"],
            :keep_metadata => %w{Required Optional ArrayElementType SkipProperty},
            :flags => %w{
              -static-link-runtime-shared-libraries
              -compiler.show-binding-warnings=false
            },
            # Each one is translated into -compiler.item_name
            :compiler_flags => compiler_flags
          )
        ensure
          File.modify(version_file) do |contents|
            contents.sub(
              %Q{VERSION: String = "#{build}"}, 
              %Q{VERSION: String = "#{old_version}"}
            )
          end
        end
      end
    end
  end

  compile_deps = ["build:compile:assets", "build:compile:swf"]
  desc "Compile assets and SWF."
  task :compile => compile_deps

  namespace :copy do
    desc "Copy SWF with prepared html-template to #{dist_dir}"
    task :swf do
      info "Cleaning #{dist_dir}"
      FileUtils.rm_rf dist_dir
      FileUtils.mkdir_p dist_dir

      info "Copying SWF"
      FileUtils.cp bin_swf, dist_dir
      FileUtils.cp bin_version, dist_dir

      info "Copying html-template"
      html_files.each do |path|
        FileUtils.cp_r path, dist_dir
      end

      checksums = %W{game.js #{swf_name}.swf}.inject({}) do |hash, file|
        info "Checksuming and moving #{file}"
        path = "#{dist_dir}/#{file}"
        hash[file] = checksum(path)
        FileUtils.mv(
          path,
          "#{dist_dir}/#{append_checksum(file, hash[file])}"
        )
        hash
      end

      info "Processing index.html"
      index_html = "#{dist_dir}/index.html"
      FileUtils.mv("#{dist_dir}/index.template.html", index_html)
      FileUtils.copy("#{html_extras_dir}/htaccess.template",
                     "#{dist_dir}/.htaccess")
      File.modify(index_html) do |content|
        {
          "${gamejs.checksum}" => checksums["game.js"],
          "${swf.checksum}" => checksums["#{swf_name}.swf"],
          "${flashVersion}" => FLASH_VERSION,
          "binDebug: true" => "binDebug: false"
        }.each { |from, to| content.gsub!(from, to) }

        content
      end
    end

    desc "Copy and checksum locales from html-template to #{dist_locale_dir}"
    task :locales do
      copy_and_checksum(locale_dir, "*.xml", dist_locale_dir)
    end

    desc "Copy and checksum assets from src/assets to #{dist_locale_dir}"
    task :assets do
      copy_and_checksum(compiled_assets_dir, "*.swf", dist_assets_dir)
      copy_and_checksum(
        "#{raw_assets_dir}/unbundled", "**/*.*",
        File.join(dist_assets_dir, 'unbundled')
      )
    end

    desc "Copy and checksum assets from src/assets to #{src_dir}/assets"
    task :"assets-dev" do
      copy_glob(compiled_assets_dir, "*.swf", src_assets_dir)
      copy_glob(
        "#{raw_assets_dir}/unbundled", "**/*.*",
        File.join(src_assets_dir, 'unbundled')
      )
    end
  end

  copy_deps = ["build:copy:swf", "build:copy:locales", "build:copy:assets"]
  desc "Copy SWF, locales and assets to #{dist_dir}"
  task :copy => copy_deps

  desc "Generate a build ready for distribution"
  task :dist do
    columns = 50
    times = []
    (prepare_deps + compile_deps + copy_deps).each do |task|
      start_time = Time.now
      Rake::Task[task].invoke
      time_taken = Time.now - start_time
      times.push [task, time_taken]
    end
    info "Dist build complete."
    info ""
    info "Time taken:"
    info "-" * columns
    times.each do |task_name, time_taken|
      info "  %-#{columns - 11}s %5.1fs" % [task_name, time_taken]
    end
    info "-" * columns
    info "%#{columns - 4}s" % [
      "Total: %5.1fs" %
        times.inject(0.0) { |sum, (_, time_taken)| sum + time_taken}
    ]
  end

  namespace :dist do
    desc "Generate a build ready for distribution (but clean up at first)"
    task :clean => ["build:clean", "build:dist"]
  end
end
