#!/usr/bin/env ruby
require 'pathname'

# For graphing director statuses.

require File.expand_path(
  File.dirname(Pathname.new(__FILE__).realpath) +
  '/../../lib/server/control_client.rb'
)

begin
  client = ControlClient.new

  data = client.message("director_stats")

  if ARGV[0] == "config"
    puts "graph_title Enqueued director tasks"
    puts "graph_category nebula44"
    puts "graph_args --base 1000 -l 0"
    puts "graph_vlabel Tasks enqueued"
    data["stats"].each do |director, _|
      puts "#{director}.label #{director} director"
      puts "#{director}.type GAUGE"
      puts "#{director}.min 0"
    end
  else
    data["stats"].each do |director, value|
      puts "#{director}.value #{value}"
    end
  end
rescue ControlClient::ConnectionError
  STDERR.write("Cannot connect to server!\n")
  exit 2
end