---
# How much victory points you need to win the game?
victory.condition: 1250000

# Battles which happen in battleground against other players give
# VPs to players.
battle.victory_points: (damage_dealt_to_space * 0.25 + damage_dealt_to_ground) * 0.06 * fairness_multiplier
# They also give out creds.
battle.creds: victory_points / 2.0
