---
# How much victory points you need to win the game?
victory.condition: 35000

# How much victory points you get for planet takeover?
planet.takeover.vps: 5

# Bonus for planet occupation.
# [type, count]
planet.bonus:
  - [thor, 1]
  - [dirac, 2]
  - [spudder, 1]
  - [glancer, 1]
  - [gnat, 3]

# Must be .0, spacemule expects double
planet.metal.storage: 100000.0
planet.energy.storage: 200000.0
planet.zetium.storage: 25000.0
