---
# How much victory points you need to win the game?
victory.condition: 35000

# How much victory points you get for planet takeover?
planet.takeover.vps: 5

# Bonus for planet occupation.
# [type, count]
planet.bonus:
  - [thor, 4]
  - [dirac, 8]
  - [gnawer, 2]
  - [spudder, 4]
  - [glancer, 4]
  - [gnat, 10]
