---
# How much victory points you need to win the game?
victory.condition: 35000

# How much victory points you get for planet takeover?
planet.takeover.vps: 5

# Bonus for planet occupation.
# [type, count]
planet.bonus:
  - [demosis, 1]
  - [thor, 8]
  - [dirac, 15]
  - [gnawer, 2]
  - [spudder, 8]
  - [glancer, 6]
  - [gnat, 15]
