---

# How much numbers after . should we keep?
resources.rounding_precision: 4
<% 
  br_metal = 0.005
  br_energy = 0.01
  br_zetium = 0.001
%>

# How much constructor mods can reduce construction time to?
# I.e. 5 would mean that min construction time can be 5%.
constructor.min_time_percentage: 5

# building.trait_name.property

# name, width, height, hp, units
#
# units:
#  flank0, flank1, flank2
#
# Supported units: Gnat, Glancer, Spudder, Gnawer
#
<% [
  ["metal_extractor", 2, 2, 400,
    [
      ["gnat"] * 5,
      ["glancer"] * 2
    ]
  ],
  ["geothermal_plant", 2, 2, 600,
    [
      ["gnat"] * 5 + ["glancer"] * 2,
      ["glancer"] * 2 + ["gnat"] * 3
    ]
  ],
  ["zetium_extractor", 2, 2, 800,
    [
      ["gnat"] * 5 + ["glancer"] * 2,
      ["glancer"] * 2 + ["gnat"] * 3
    ]
  ],
  ["solar_plant", 2, 2, 1000,
    [
      ["gnat"] * 5 + ["glancer"] * 2,
      ["glancer"] * 2 + ["gnat"] * 3
    ]
  ],
  ["communications_hub", 3, 2, 1200,
    [
      ["gnat"] * 5 + ["glancer"] * 2,
      ["glancer"] * 2 + ["gnat"] * 3
    ]
  ],
  ["temple", 3, 3, 1500,
    [
      ["gnat"] * 5 + ["glancer"] * 2,
      ["glancer"] * 2 + ["gnat"] * 3
    ]
  ],
  ["excavation_site", 4, 4, 2000,
    [
      ["gnat"] * 5 + ["glancer"] * 2,
      ["glancer"] * 2 + ["gnat"] * 3
    ]
  ],
  ["research_center", 4, 4, 4000,
    [
      ["gnat"] * 5 + ["glancer"] * 2,
      ["glancer"] * 2 + ["gnat"] * 3
    ]
  ],
  ["jumpgate", 5, 5, 8000,
    [
      ["gnat"] * 5 + ["glancer"] * 2,
      ["glancer"] * 2 + ["gnat"] * 3
    ]
  ],
].each do |name, width, height, hp, units| %>

npc_<%= name %>.width: <%= width %>
npc_<%= name %>.height: <%= height %>
npc_<%= name %>.hp: <%= hp %>
npc_<%= name %>.max_level: 1
npc_<%= name %>.npc: true
npc_<%= name %>.constructable: false
npc_<%= name %>.units: <%= units.inspect %>

<% end %>

mothership.constructable: false
mothership.width: 8
mothership.height: 6
mothership.upgrade_time: 0
mothership.max_level: 1 # autogenerated by odsimport
mothership.hp: 10500
mothership.metal.generate: 0.0279 # autogenerated by odsimport
mothership.metal.store: 9642.24 # autogenerated by odsimport
mothership.metal.starting: 1.0 # autogenerated by odsimport
mothership.energy.generate: 0.0617 # autogenerated by odsimport
mothership.energy.store: 21323.52 # autogenerated by odsimport
mothership.energy.starting: 1.0 # autogenerated by odsimport
mothership.zetium.store: 2626.56 # autogenerated by odsimport
mothership.zetium.generate: 0.0
mothership.zetium.starting: 1.0 # autogenerated by odsimport
mothership.queue.max: 2
mothership.constructor.items:
  - building/*

headquarters.constructable: false
headquarters.width: 4
headquarters.height: 6
headquarters.max_level: 1 # autogenerated by odsimport
headquarters.upgrade_time: 3600.0 # autogenerated by odsimport
headquarters.hp: 5000
headquarters.metal.generate: 0.00837 # autogenerated by odsimport
headquarters.metal.store: 2892.672 # autogenerated by odsimport
headquarters.energy.generate: 0.01851 # autogenerated by odsimport
headquarters.energy.store: 6397.056 # autogenerated by odsimport
headquarters.zetium.store: 787.968 # autogenerated by odsimport
headquarters.queue.max: 1
headquarters.constructor.items:
  - building/*

metal_extractor.width: 2
metal_extractor.height: 2
metal_extractor.max_level: 10 # autogenerated by odsimport
metal_extractor.upgrade_time: -340.0 + 175.0 * (level + 2.0) + level ** 4.0 + 2.0 ** (level + 3.0) # autogenerated by odsimport
metal_extractor.hp: 1000 + 500 * (level - 1)
metal_extractor.metal.cost: (level + 0.1 * level ** 1.1 + 2.0 ** (level + -1.0)) * 10.0 # autogenerated by odsimport
metal_extractor.energy.cost: (0.5 * level + 0.1 * level ** 1.1 + 2.0 ** (level + -1.0)) * 50.0 # autogenerated by odsimport
metal_extractor.metal.generate: (level + 0.1 * level ** 1.1) * 0.005 # autogenerated by odsimport
metal_extractor.energy.use: (0.5 * level + 0.1 * level ** 1.1) * 0.0066 # autogenerated by odsimport
metal_extractor.constructable.position: 0

### metal_extractor_t2 config ###

# Dimensions
metal_extractor_t2.width: 2
metal_extractor_t2.height: 2

# Hit points
metal_extractor_t2.hp: 300

# Upgrades
metal_extractor_t2.max_level: 4 # autogenerated by odsimport
metal_extractor_t2.upgrade_time: -4000.0 + 1500.0 * (level + 3.0) + (level + 5.0) ** 5.0 + 3.0 ** (level + 6.0) # autogenerated by odsimport
metal_extractor_t2.metal.cost: (-100.0 + 1.6 * level + level ** 1.5 + 3.0 ** (level + 4.0)) * 1.6 # autogenerated by odsimport
metal_extractor_t2.metal.generate: (6.0 + 1.6 * level + 0.5 * level ** 1.5) * 0.005 # autogenerated by odsimport
metal_extractor_t2.energy.cost: (3.0 + 10.0 * (level + -3.0) + (level + -0.2) ** 2.0 + 2.0 ** (level + 3.4)) * 216.0 # autogenerated by odsimport
metal_extractor_t2.energy.use: (4.0 + 0.8 * level + 0.2 * (level + -0.2) ** 1.45) * 0.0066 # autogenerated by odsimport
metal_extractor_t2.zetium.cost: (0.14 * level + 0.01 * level ** 1.1) * 140.0 # autogenerated by odsimport

# Technology requirements
metal_extractor_t2.requirement.metal_extractor_t2.level: 1

# Position in constructable list
metal_extractor_t2.constructable.position: 1

metal_storage.width: 2
metal_storage.height: 2
metal_storage.max_level: 8 # autogenerated by odsimport
metal_storage.upgrade_time: -1200.0 + 750.0 * (level + 2.0) + (level + 10.0) ** 3.0 + 2.0 ** (level + 6.0) # autogenerated by odsimport
metal_storage.hp: 900 + 400 * (level - 1)
metal_storage.metal.cost: (1500.0 + 2900.0 * (level + -1.0)) * 0.1 # autogenerated by odsimport
metal_storage.energy.cost: (1500.0 + 2900.0 * (level + -1.0)) * 0.03 # autogenerated by odsimport
metal_storage.metal.store: 1500.0 + 2900.0 * (level + -1.0) # autogenerated by odsimport
metal_storage.constructable.position: 2

wind_panel.width: 1
wind_panel.height: 3
wind_panel.max_level: 10 # autogenerated by odsimport
wind_panel.upgrade_time: -320.0 + 150.0 * (level + 2.0) + level ** 4.0 + 2.0 ** (level + 1.0) # autogenerated by odsimport
wind_panel.hp: 450 + 500 * (level - 1)
wind_panel.metal.cost: (level + 0.1 * level ** 1.1 + 2.0 ** (level + -1.0)) * 20.0 # autogenerated by odsimport
wind_panel.energy.cost: (0.5 * level + 0.1 * level ** 1.1 + 2.0 ** (level + -1.0)) * 30.0 # autogenerated by odsimport
wind_panel.energy.generate: (0.5 * level + 0.1 * level ** 1.1) * 0.02 # autogenerated by odsimport
wind_panel.constructable.position: 10

solar_plant.width: 2
solar_plant.height: 4
solar_plant.max_level: 4 # autogenerated by odsimport
solar_plant.upgrade_time: 2000.0 * (level + 3.0) + (level + 1.0) ** 3.0 + 4.0 ** (level + 4.1) # autogenerated by odsimport
solar_plant.hp: 500 + 500 * (level - 1)
solar_plant.metal.cost: (8.0 * level + 0.5 * level ** 2.2) * 180.0 # autogenerated by odsimport
solar_plant.energy.cost: (4.0 + 0.8 * level + 0.2 * (level + -0.2) ** 1.45) * 220.0 # autogenerated by odsimport
solar_plant.energy.generate: (4.0 + 0.8 * level + 0.2 * (level + -0.2) ** 1.45) * 0.02 # autogenerated by odsimport
solar_plant.zetium.cost: (-0.04 + 0.14 * level + 0.01 * level ** 1.1) * 140.0 # autogenerated by odsimport
solar_plant.requirement.collector_t2.level: 1
solar_plant.constructable.position: 11

geothermal_plant.width: 2
geothermal_plant.height: 2
geothermal_plant.max_level: 2 # autogenerated by odsimport
geothermal_plant.upgrade_time: (2000.0 * (level + 3.0) + (level + 1.0) ** 3.0 + 4.0 ** (level + 4.1)) * 1.1 # autogenerated by odsimport
geothermal_plant.hp: 300 + 500 * (level - 1)
geothermal_plant.metal.cost: (6.0 + 1.6 * level + 0.5 * level ** 1.5) * 216.0 # autogenerated by odsimport
geothermal_plant.energy.cost: (4.0 + 0.8 * level + 0.2 * (level + -0.2) ** 1.45) * 288.0 # autogenerated by odsimport
geothermal_plant.energy.generate: (7.0 * level + 0.2 * (level + 3.0) ** 2.3) * 0.02 # autogenerated by odsimport
geothermal_plant.zetium.cost: (0.14 * level + 0.01 * level ** 1.1) * 150.0 # autogenerated by odsimport
geothermal_plant.requirement.geothermal_plant.level: 1
geothermal_plant.constructable.position: 12

energy_storage.width: 2
energy_storage.height: 3
energy_storage.max_level: 8 # autogenerated by odsimport
energy_storage.upgrade_time: 400.0 * (level + 3.0) + (level + 3.0) ** 4.0 + 2.0 ** (level + 3.0) # autogenerated by odsimport
energy_storage.hp: 340 + 500 * (level - 1)
energy_storage.metal.cost: (3000.0 + 6000.0 * (level + -1.0)) * 0.03 # autogenerated by odsimport
energy_storage.energy.cost: (3000.0 + 6000.0 * (level + -1.0)) * 0.1 # autogenerated by odsimport
energy_storage.energy.store: 3000.0 + 6000.0 * (level + -1.0) # autogenerated by odsimport
energy_storage.constructable.position: 13

zetium_extractor.width: 2
zetium_extractor.height: 2
zetium_extractor.max_level: 10 # autogenerated by odsimport
zetium_extractor.upgrade_time: 200.0 + 250.0 * (level + 2.0) + (level + 3.0) ** 4.0 + 2.0 ** (level + 2.0) # autogenerated by odsimport
zetium_extractor.hp: 800 + 500 * (level - 1)
zetium_extractor.metal.cost: (level + 0.1 * level ** 1.1) * 30.0 # autogenerated by odsimport
zetium_extractor.energy.cost: (0.5 * level + 0.1 * level ** 1.1) * 223.2 # autogenerated by odsimport
zetium_extractor.zetium.generate: (0.14 * level + 0.01 * level ** 1.1) * 0.01 # autogenerated by odsimport
zetium_extractor.energy.use: (0.5 * level + 0.1 * level ** 1.1) * 0.018 # autogenerated by odsimport
zetium_extractor.requirement.zetium_extraction.level: 1
zetium_extractor.constructable.position: 20


### zetium_extractor_t2 config ###

# Dimensions
zetium_extractor_t2.width: 2
zetium_extractor_t2.height: 2

# Hit points
zetium_extractor_t2.hp: 300

# Upgrades
zetium_extractor_t2.max_level: 4 # autogenerated by odsimport
zetium_extractor_t2.upgrade_time: 14000.0 * level + level ** 4.0 + 7.0 ** (level + 2.0) # autogenerated by odsimport
zetium_extractor_t2.metal.cost: (3.0 * level + 0.5 * level ** 4.4 + 5.0 ** level) * 36.0 # autogenerated by odsimport
zetium_extractor_t2.energy.cost: -100.0 + 1400.0 * level + (level + 1.0) ** 4.0 + 4.5 ** (level + 2.0) # autogenerated by odsimport
zetium_extractor_t2.energy.use: (4.0 + 0.8 * level + 0.2 * (level + -0.2) ** 1.45) * 0.02 # autogenerated by odsimport
zetium_extractor_t2.zetium.cost: 25.0 * level + level ** 3.3 + 3.0 ** level # autogenerated by odsimport
zetium_extractor_t2.zetium.generate: (0.6 + 0.24 * level + 0.2 * level ** 1.45) * 0.01 # autogenerated by odsimport

# Technology requirements
zetium_extractor_t2.requirement.zetium_extractor_t2.level: 1

# Position in constructable list
zetium_extractor_t2.constructable.position: 21

zetium_storage.width: 3
zetium_storage.height: 3
zetium_storage.max_level: 8 # autogenerated by odsimport
zetium_storage.upgrade_time: 1000.0 + 750.0 * (level + 2.0) + (level + 3.0) ** 4.0 + 2.0 ** (level + 6.0) # autogenerated by odsimport
zetium_storage.hp: 500 + 500 * (level - 1)
zetium_storage.metal.cost: (390.0 + 1058.0 * (level + -1.0)) * 0.1 # autogenerated by odsimport
zetium_storage.energy.cost: (390.0 + 1058.0 * (level + -1.0)) * 0.03 # autogenerated by odsimport
zetium_storage.zetium.cost: (390.0 + 1058.0 * (level + -1.0)) * 0.1 # autogenerated by odsimport
zetium_storage.zetium.store: 390.0 + 1058.0 * (level + -1.0) # autogenerated by odsimport
zetium_storage.requirement.zetium_extraction.level: 1
zetium_storage.constructable.position: 22

barracks.width: 3
barracks.height: 3
barracks.max_level: 4 # autogenerated by odsimport
barracks.upgrade_time: 2940.0 + 7350.0 * (level + -1.0) # autogenerated by odsimport
barracks.hp: 1400 + 500 * (level - 1)
barracks.metal.cost: 2260.0 + 2712.0 * (level + -1.0) # autogenerated by odsimport
barracks.energy.cost: 4520.0 + 5424.0 * (level + -1.0) # autogenerated by odsimport
barracks.queue.max: 4
barracks.mod.construction: 20.0 * (level + -1.0) # autogenerated by odsimport
barracks.constructor.items:
  - unit/trooper
  - unit/shocker
  - unit/seeker
# TODO: move to covert ops.
#  - unit/spy
#  - unit/saboteur
barracks.constructable.position: 100


### ground_factory config ###

# Dimensions
ground_factory.width: 5
ground_factory.height: 5

# Hit points
ground_factory.hp: 2000

# Upgrades
ground_factory.max_level: 4 # autogenerated by odsimport
ground_factory.upgrade_time: 17220.0 + 43050.0 * (level + -1.0) # autogenerated by odsimport
ground_factory.metal.cost: 8217.98 + 9861.57 * (level + -1.0) # autogenerated by odsimport
ground_factory.energy.cost: 16435.95 + 19723.14 * (level + -1.0) # autogenerated by odsimport
ground_factory.zetium.cost: 547.87 + 657.44 * (level + -1.0) # autogenerated by odsimport

# Technology requirements
ground_factory.requirement.ground_factory.level: 1

# Position in constructable list
ground_factory.constructable.position: 110

# Items that I can build
ground_factory.queue.max: 3
ground_factory.mod.construction: 20.0 * (level + -1.0) # autogenerated by odsimport
ground_factory.constructor.items:
  - unit/scorpion
  - unit/azure
#  - unit/mantis
#  - unit/tremor
#  - unit/zeus
  - unit/mdh
#  - unit/terraformer

### space_factory config ###

# Dimensions
space_factory.width: 6
space_factory.height: 4

# Hit points
space_factory.hp: 4000

# Upgrades
space_factory.max_level: 4 # autogenerated by odsimport
space_factory.upgrade_time: 21210.0 + 53025.0 * (level + -1.0) # autogenerated by odsimport
space_factory.metal.cost: 14343.75 + 17212.5 * (level + -1.0) # autogenerated by odsimport
space_factory.energy.cost: 20081.25 + 24097.5 * (level + -1.0) # autogenerated by odsimport
space_factory.zetium.cost: 1004.06 + 1204.88 * (level + -1.0) # autogenerated by odsimport

# Technology requirements
space_factory.requirement.space_factory.level: 1

# Position in constructable list
space_factory.constructable.position: 120

# Items that I can build
space_factory.queue.max: 3
space_factory.mod.construction: 20.0 * (level + -1.0) # autogenerated by odsimport
space_factory.constructor.items:
  - unit/mule
  - unit/crow
  - unit/cyrix
  - unit/rhyno
  - unit/dart
  - unit/avenger

### research_center config ###

research_center.width: 4
research_center.height: 4
research_center.max_level: 6 # autogenerated by odsimport
research_center.upgrade_time: 18000.0 + 19800.0 * (level + -1.0) # autogenerated by odsimport
research_center.hp: 5000
research_center.metal.cost: 0.0 # autogenerated by odsimport
research_center.energy.cost: 0.0 # autogenerated by odsimport
research_center.zetium.cost: 0.0 # autogenerated by odsimport
research_center.scientists: 36.0 + 14.0 * (level + -1.0) + level + 2.0 ** (level + 1.0) # autogenerated by odsimport
research_center.constructable.position: 200

radar.width: 4
radar.height: 4
radar.max_level: 2 # autogenerated by odsimport
radar.upgrade_time: 10800.0 + 259200.0 * (level + -1.0) # autogenerated by odsimport
radar.hp: 3000
radar.metal.cost: 4821.12 + 96422.4 * (level + -1.0) # autogenerated by odsimport
radar.energy.cost: 10661.76 + 213235.2 * (level + -1.0) # autogenerated by odsimport
radar.zetium.cost: 656.64 + 13132.8 * (level + -1.0) # autogenerated by odsimport
radar.radar.strength: 3.0 + 3.0 * (level + -1.0) # autogenerated by odsimport
radar.energy.use: 0.0989 + 0.075 * (level + -1.0) # autogenerated by odsimport
radar.requirement.radar.level: 1
radar.constructable.position: 210

#resource_transporter.width: 2
#resource_transporter.height: 2
#resource_transporter.max_level: 1
#resource_transporter.upgrade_time: (<%= 1.minute + 20.seconds %> + 10 * (level - 1))  / speed
#resource_transporter.hp: 300 + 500 * (level - 1)
#resource_transporter.metal.cost: 100 * (level + 1)
#resource_transporter.energy.cost: 200 * (level + 1)
#resource_transporter.requirement.resource_transporter.level: 1
#resource_transporter.constructable.position: 230

##################################
###           TOWERS           ###
##################################

### vulcan config ###

# Dimensions
vulcan.width: 2
vulcan.height: 2

# Hit points
vulcan.hp: 1000 # autogenerated by odsimport

# Upgrades
vulcan.max_level: 1
vulcan.upgrade_time: 5460 # autogenerated by odsimport
vulcan.metal.cost: 3187.81 # autogenerated by odsimport
vulcan.energy.cost: 3923.46 # autogenerated by odsimport
vulcan.zetium.cost: 306.52 # autogenerated by odsimport

# Technology requirements
vulcan.requirement.vulcan.level: 1

# Position in constructable list
vulcan.constructable.position: 300

# Battlefield combat properties
vulcan.xp_modifier: 1.0 # autogenerated by odsimport
vulcan.initiative: 7 # autogenerated by odsimport
vulcan.guns: [{"reach": "ground", "period": 1, "damage": "piercing", "dpt": 23}, {"reach": "ground", "period": 1, "damage": "piercing", "dpt": 23}, {"reach": "ground", "period": 1, "damage": "piercing", "dpt": 23}, {"reach": "ground", "period": 1, "damage": "piercing", "dpt": 23}, {"reach": "ground", "period": 1, "damage": "piercing", "dpt": 23}, {"reach": "ground", "period": 1, "damage": "piercing", "dpt": 23}] # autogenerated by odsimport

### screamer config ###

# Dimensions
screamer.width: 2
screamer.height: 2

# Hit points
screamer.hp: 1300 # autogenerated by odsimport

# Upgrades
screamer.max_level: 1
screamer.upgrade_time: 7320 # autogenerated by odsimport
screamer.metal.cost: 5376.8 # autogenerated by odsimport
screamer.energy.cost: 6617.6 # autogenerated by odsimport
screamer.zetium.cost: 517.0 # autogenerated by odsimport

# Technology requirements
screamer.requirement.screamer.level: 1

# Position in constructable list
screamer.constructable.position: 310

# Battlefield combat properties
screamer.xp_modifier: 1.0 # autogenerated by odsimport
screamer.initiative: 10 # autogenerated by odsimport
screamer.guns: [{"reach": "ground", "period": 1, "damage": "explosive", "dpt": 96}, {"reach": "ground", "period": 1, "damage": "explosive", "dpt": 96}] # autogenerated by odsimport

### thunder config ###

# Dimensions
thunder.width: 2
thunder.height: 2

# Hit points
thunder.hp: 2000 # autogenerated by odsimport

# Upgrades
thunder.max_level: 1
thunder.upgrade_time: 15360 # autogenerated by odsimport
thunder.metal.cost: 6170.74 # autogenerated by odsimport
thunder.energy.cost: 7594.75 # autogenerated by odsimport
thunder.zetium.cost: 593.34 # autogenerated by odsimport

# Technology requirements
thunder.requirement.thunder.level: 1

# Position in constructable list
thunder.constructable.position: 320

# Battlefield combat properties
thunder.xp_modifier: 1.0 # autogenerated by odsimport
thunder.initiative: 4 # autogenerated by odsimport
thunder.guns: [{"reach": "space", "period": 1, "damage": "explosive", "dpt": 523}] # autogenerated by odsimport
