---
# Everything related to monetization of the game.

# 1 LTL/EUR/USD equals to 2000 creds.

# [time, cost]
upgradable.speed_up:
  - [<%= 1.hour %>, 100]
  - [<%= 2.hours %>, 200]
  - [<%= 6.hours %>, 500]
  - [<%= 12.hours %>, 750]
  - [<%= Creds::ACCELERATE_INSTANT_COMPLETE %>, 1000]

# Cost to move building from one spot to another
building.move: 200
# Cost to destroy building if cooldown is on.
building.destroy: 300

# Cost to change alliance data.
alliance.change: 1000

# How much creds does speeding up down to 0 cost?
move.speed_up: 1000

# How much % does boost give to resources?
planet.resources.boost: 25
# How long does it last?
planet.resources.boost.duration: <%= 1.week %>
# How much does it cost?
planet.resources.boost.cost: 1700

# Vip [cost, creds per tick]
# Vips are enumerated in an ascending order.
vip:
  - [2500, 700]
  - [4500, 1600]
  - [6500, 3000]

# How long does VIP last?
vip.duration: <%= 1.week %>
# How often it is refreshed?
vip.tick.duration: <%= 1.day %>
