---
# Everything related to monetization of the game.

# 1 LTL/EUR/USD equals to 2000 creds.

# [time, cost]
upgradable.speed_up:
  - [<%= 1.hour %> / speed, 200]
  - [<%= 2.hours %> / speed, 300]
  - [<%= 6.hours %> / speed, 500]
  - [<%= 12.hours %> / speed, 750]
  - [<%= 1.day %> / speed, 1000]
  - [<%= 2.days %> / speed, 1500]
  - [<%= Creds::ACCELERATE_INSTANT_COMPLETE %>, 2000]

# How much does it cost to remove a foliage.
foliage.remove: 1000.0 * width * height / 9

# How much creds it costs to explore something. Result from this formula
# should be rounded.
exploration.finish: 20.0 * width * height / 9

# Cost to move building from one spot to another
building.move: 200
# Cost to destroy building if cooldown is on.
building.destroy: 300

# Cost to change alliance data.
alliance.change: 1000

# How much creds does speeding up down to 0 cost?
# Data for formula entered below.
# pp (1..20).map { |c| [c, [0.2, 0.4, 0.6, 0.8].map { |h| [h, (100 + (100 * c) * h + 100 * h * h).round] } ] };nil
#
#[[1, [[0.2, 124], [0.4, 156], [0.6, 196], [0.8, 244]]],
# [2, [[0.2, 144], [0.4, 196], [0.6, 256], [0.8, 324]]],
# [3, [[0.2, 164], [0.4, 236], [0.6, 316], [0.8, 404]]],
# [4, [[0.2, 184], [0.4, 276], [0.6, 376], [0.8, 484]]],
# [5, [[0.2, 204], [0.4, 316], [0.6, 436], [0.8, 564]]],
# [6, [[0.2, 224], [0.4, 356], [0.6, 496], [0.8, 644]]],
# [7, [[0.2, 244], [0.4, 396], [0.6, 556], [0.8, 724]]],
# [8, [[0.2, 264], [0.4, 436], [0.6, 616], [0.8, 804]]],
# [9, [[0.2, 284], [0.4, 476], [0.6, 676], [0.8, 884]]],
# [10, [[0.2, 304], [0.4, 516], [0.6, 736], [0.8, 964]]],
# [11, [[0.2, 324], [0.4, 556], [0.6, 796], [0.8, 1044]]],
# [12, [[0.2, 344], [0.4, 596], [0.6, 856], [0.8, 1124]]],
# [13, [[0.2, 364], [0.4, 636], [0.6, 916], [0.8, 1204]]],
# [14, [[0.2, 384], [0.4, 676], [0.6, 976], [0.8, 1284]]],
# [15, [[0.2, 404], [0.4, 716], [0.6, 1036], [0.8, 1364]]],
# [16, [[0.2, 424], [0.4, 756], [0.6, 1096], [0.8, 1444]]],
# [17, [[0.2, 444], [0.4, 796], [0.6, 1156], [0.8, 1524]]],
# [18, [[0.2, 464], [0.4, 836], [0.6, 1216], [0.8, 1604]]],
# [19, [[0.2, 484], [0.4, 876], [0.6, 1276], [0.8, 1684]]],
# [20, [[0.2, 504], [0.4, 916], [0.6, 1336], [0.8, 1764]]]]
move.speed_up: (100 + (100 * hop_count) * percentage + 100 * percentage ** 2)
move.speed_up.max_cost: 2500

# How much % does boost give to resources?
planet.resources.boost: 25
# How long does it last?
planet.resources.boost.duration: <%= 1.week %>
# How much does it cost?
planet.resources.boost.cost: 2000

# Vip [cost, creds per tick, vip duration]
# Vips are enumerated in an ascending order.
vip:
  # VIP1, x2
  - [5000,  1450, <%= 1.week %>]
  # VIP2, x3
  - [10000, 2150, <%= 2.weeks %>]
  # VIP3, x4
  - [20000, 2900, <%= 4.weeks %>]    

# How often it is refreshed?
vip.tick.duration: <%= 1.day %>
