---
# Everything related to monetization of the game.

# 1 LTL/EUR/USD equals to 2000 creds.

# [time, cost]
upgradable.speed_up:
  - [<%= 1.hour %> / speed, 200]
  - [<%= 2.hours %> / speed, 300]
  - [<%= 6.hours %> / speed, 500]
  - [<%= 12.hours %> / speed, 750]
  - [<%= Creds::ACCELERATE_INSTANT_COMPLETE %>, 1000]

# Cost to move building from one spot to another
building.move: 200
# Cost to destroy building if cooldown is on.
building.destroy: 300

# Cost to change alliance data.
alliance.change: 1000

# How much creds does speeding up down to 0 cost?
move.speed_up: 1000

# How much % does boost give to resources?
planet.resources.boost: 25
# How long does it last?
planet.resources.boost.duration: <%= 1.week %>
# How much does it cost?
planet.resources.boost.cost: 2000

# Vip [cost, creds per tick, vip duration]
# Vips are enumerated in an ascending order.
vip:
  # VIP1, x2
  - [5000,  1450, <%= 1.week %>]
  # VIP2, x3
  - [10000, 2150, <%= 2.weeks %>]
  # VIP3, x4
  - [20000, 2900, <%= 4.weeks %>]    

# How often it is refreshed?
vip.tick.duration: <%= 1.day %>
