---
# Everything related to monetization of the game.

# 1 LTL/EUR/USD equals to 2000 creds.

# [time, cost]
upgradable.speed_up:
  - [<%= 2.hours %>, 200]
  - [<%= 6.hours %>, 500]
  - [<%= 12.hours %>, 750]
  - [<%= Creds::ACCELERATE_INSTANT_COMPLETE %>, 1000]

# Cost to move building from one spot to another
building.move: 200
# Cost to destroy building if cooldown is on.
building.destroy: 300

# Cost to change alliance data.
alliance.change: 1000

# Vip [cost, creds daily]
# Vips are enumerated in an ascending order.
vip:
  - [3000, 850]
  - [5000, 1800]
  - [6000, 3000]