---
cooldown: <%= 1.day %>

# Point ranges for rewards.
ranges:
  - ["noob", 0, 20000]
  - ["beginner", 20000, 50000]
  - ["intermediate", 50000, 100000]
  - ["advanced", 100000, 250000]
  - ["expert", 250000, null]
  
# types:
#  ["unit", _type_, _level_]
#  ["creds", _count_]
#  ["metal", _count_]
#  ["energy", _count_]
#  ["zetium", _count_]
range.noob:
  - [unit, Shocker, 2]
  - [unit, Seeker, 2]
  - [unit, Glancer, 1]
  - [unit, Trooper, 2]
  - [unit, Trooper, 1]
  - [unit, Trooper, 1]
  - [unit, Gnat, 1]
  - [unit, Gnat, 1]
  - [unit, Gnat, 1]
range.beginner:
  - [unit, Shocker, 2]
  - [unit, Seeker, 2]
  - [unit, Trooper, 2]
  - [unit, Spudder, 1]
  - [unit, Glancer, 1]
  - [unit, Gnat, 1]
  - [creds, 250]
  - [creds, 100]
  - [creds, 100]
  - [metal, 1000]
  - [metal, 500]
  - [energy, 2000]
  - [energy, 1000]
  - [energy, 500]
  - [zetium, 500]
  - [zetium, 200]
  - [zetium, 100]
range.intermediate:
  - [unit, Scorpion, 2]
  - [unit, Shocker, 3]
  - [unit, Shocker, 3]
  - [unit, Seeker, 3]
  - [unit, Trooper, 5]
  - [unit, Gnawer, 1]
  - [unit, Spudder, 1]
  - [unit, Glancer, 1]
  - [unit, Gnat, 1]
  - [creds, 500]
  - [creds, 250]
  - [creds, 100]
  - [metal, 2000]
  - [metal, 1000]
  - [energy, 2000]
  - [energy, 1000]
  - [zetium, 500]
  - [zetium, 200]
range.advanced:
  - [unit, Thor, 1]
  - [unit, Dirac, 1]
  - [unit, Crow, 3]
  - [unit, Cyrix, 2]
  - [unit, Mule, 3]
  - [unit, Scorpion, 3]
  - [unit, Azure, 3]
  - [unit, Shocker, 3]
  - [unit, Seeker, 3]
  - [unit, Gnawer, 1]
  - [unit, Spudder, 1]
  - [creds, 750]
  - [creds, 500]
  - [creds, 250]
  - [creds, 100]
  - [metal, 4000]
  - [metal, 2000]
  - [metal, 1000]
  - [energy, 6000]
  - [energy, 4000]
  - [energy, 2000]
  - [zetium, 2000]
  - [zetium, 1000]
  - [zetium, 500]
range.expert:
  - [unit, Rhyno, 1]
  - [unit, Demosis, 1]
  - [unit, Thor, 1]
  - [unit, Dirac, 1]
  - [unit, Avenger, 3]
  - [unit, Dart, 3]
  - [unit, Crow, 5]
  - [unit, Cyrix, 3]
  - [unit, Mule, 3]
  - [unit, Scorpion, 3]
  - [unit, Azure, 3]
  - [unit, Gnawer, 1]
  - [unit, Spudder, 1]
  - [creds, 1000]
  - [creds, 750]
  - [creds, 500]
  - [creds, 500]
  - [creds, 250]
  - [metal, 12000]
  - [metal, 8000]
  - [metal, 6000]
  - [metal, 4000]
  - [energy, 12000]
  - [energy, 8000]
  - [energy, 6000]
  - [energy, 4000]
  - [zetium, 12000]
  - [zetium, 8000]
  - [zetium, 6000]
  - [zetium, 4000]
  - [zetium, 2000]