---
ranges:
  - ["noob", 0, 5000]
  - ["beginner", 5000, 10000]
  - ["intermediate", 10000, 25000]
  - ["advanced", 25000, 100000]
  - ["expert", 100000, nil]
  
range.noob:
  # [type, level]
  units:
    - [Shocker, 2]
    - [Seeker, 2]
    - [Glancer, 1]
    - [Trooper, 2]
    - [Trooper, 1]
    - [Trooper, 1]
    - [Gnat, 1]
    - [Gnat, 1]
    - [Gnat, 1]
range.beginner:
  units:
    - [Shocker, 2]
    - [Seeker, 2]
    - [Trooper, 2]
    - [Spudder, 1]
    - [Glancer, 1]
    - [Gnat, 1]
  creds: [50, 25, 25]
  metal: [1000, 500]
  energy: [2000, 1000, 500]
  zetium: [500, 200, 100]
range.intermediate:
  units:
    - [Scorpion, 2]
    - [Shocker, 3]
    - [Shocker, 3]
    - [Seeker, 3]
    - [Trooper, 5]
    - [Gnawer, 1]
    - [Spudder, 1]
    - [Glancer, 1]
    - [Gnat, 1]
  creds: [100, 50]
  metal: [2000, 1000]
  energy: [2000, 1000]
  zetium: [500, 200]
range.advanced:
  units:
    - [Thor, 1]
    - [Dirac, 1]
    - [Crow, 3]
    - [Cyrix, 2]
    - [Mule, 3]
    - [Scorpion, 3]
    - [Azure, 3]
    - [Shocker, 3]
    - [Seeker, 3]
    - [Gnawer, 1]
    - [Spudder, 1]
  creds: [100, 50]
  metal: [4000, 2000, 1000]
  energy: [6000, 4000, 2000]
  zetium: [2000, 1000, 500]
range.expert:
  units:
    - [Rhyno, 1]
    - [Demosis, 1]
    - [Thor, 1]
    - [Dirac, 1]
    - [Avenger, 3]
    - [Dart, 3]
    - [Crow, 5]
    - [Cyrix, 3]
    - [Mule, 3]
    - [Scorpion, 3]
    - [Azure, 3]
    - [Gnawer, 1]
    - [Spudder, 1]
  creds: [150, 100, 50]
  metal: [12000, 8000, 6000, 4000]
  energy: [12000, 8000, 6000, 4000]
  zetium: [12000, 8000, 6000, 4000, 2000]