---
######
# Galaxy configuration
######

# Diameter of starting zone
zone.diameter: 4
# Players per zone.
zone.players: 10

# Expansions per homeworld
expansion_systems.number: 1
# Resource systems per homeworld
resource_systems.number: 1
