---
######
# Galaxy configuration
######

# Diameter of starting zone
zone.diameter: 3

# Expansions per homeworld
expansion_systems.number: 2
# Resource systems per homeworld
resource_systems.number: 1