---
######
# Galaxy configuration
######

# Diameter of starting zone
zone.diameter: 5
# Players per zone.
zone.players: 16

# Expansions per zone
expansion_systems.number: 1
# Resource systems per zone
resource_systems.number: 1
# Wormholes to battleground per zone
wormholes.number: 2
