---
######
# Galaxy configuration
######

# From which slot start spawning? Bigger number mea
zone.start_slot: 2 # Start from 2, leave 4 center zones empty
# Diameter of starting zone
zone.diameter: 8
# Players per zone.
zone.players: 20
# Don't spawn users into zones which have home solar systems with players older
# than this time.
zone.maturity_age: <%= 1.week %>

# Free population given to player upon creation
player.population: 60
# Maximum population player can have.
player.population.max: 2500
player.inactivity_check:
- [1, <%= 10.minutes %> / speed]
- [1000, <%= 1.hour %> / speed]
- [10000, <%= 1.day %> / speed]
- [25000, <%= 2.days %> / speed]
- [100000, <%= 3.days %> / speed]
- [250000, <%= 5.days %> / speed]
- [500000, <%= 10.days %> / speed]
- [1000000, <%= 14.days %> / speed]

# How much points do you need to trigger referral callback?
# This one is also defined in web configuration.
player.referral.points_needed: 150000

# Quiet time before apocalypse.
apocalypse.quiet_time: <%= 6.days %> / speed
# How much creds you get for each day survived in apocalypse. Days are counted
# from 1.
apocalypse.survival_bonus: days * 2000

# All positions are relative to zone and not overridable in other sets!
#
# If you add any position types here, don't forget to add them to SpaceMules
# Zone#playerCount method.

# Positions of free solar systems.
free_systems.positions:
  - [0, 1]
  - [0, 4]
  - [0, 7]
  - [3, 3]
  - [3, 6]
  - [4, 0]
  - [4, 5]
  - [5, 1]
  - [7, 2]
# Positions of wormholes to battleground.
wormholes.positions:
  - [1, 6]
  - [2, 1]
  - [6, 3]
  - [5, 7]
# Positions of mini battlegrounds.
mini_battlegrounds.positions:
  - [1, 2]
  - [2, 5]
  - [6, 5]
  - [7, 0]
  
convoy.time: <%= 4.hours %> / speed
# Speed modifier for convoy ships.
convoy.speed_modifier: 6
# - [count_from, count_to, type, flank]
#
# count numbers are inclusive.
convoy.units:
  - [0, 10, Dirac, 0]
  - [1, 10, Dirac, 1]
  - [0, 5, Thor, 0]
  - [0, 10, Thor, 1]
  - [0, 4, Demosis, 0]
  - [0, 2, Demosis, 1]
  - [1, 2, ConvoyShip, 0]