---
######
# Galaxy configuration
######

# Diameter of starting zone
zone.diameter: 8
# Players per zone.
zone.players: 16

# Expansions per zone
expansion_systems.number: 1
# Resource systems per zone
resource_systems.number: 1
# Positions of wormholes to battleground. Relative to zone.
wormholes.positions:
  - [1, 6]
  - [2, 1]
  - [6, 3]