---
######
# Galaxy configuration
######

# Diameter of starting zone
zone.diameter: 8
# Players per zone.
zone.players: 20

# How long initial shield lasts on players home solar system?
player.shield_duration: <%= 2.weeks %> / speed
# Free population given to player upon creation
player.population: 60
# Maximum population player can have.
player.population.max: 2500
# When should the inactivity check be scheduled for?
player.inactivity_check: <%= 1.week %> / speed
# How much points must player have to be considered active?
player.inactivity_check.points: 15000
# How recent should last player login be if he doesn't have enough points?
player.inactivity_check.last_login_in: <%= 3.days %> / speed

# How much points do you need to trigger referral callback?
# This one is also defined in web configuration.
player.referral.points_needed: 150000

# All positions are relative to zone and not overridable in other sets!
#
# If you add any position types here, don't forget to add them to SpaceMules
# Zone#playerCount method.

# Positions of expansion systems.
expansion_systems.positions:
  - [2, 4]
# Positions of resource systems.
resource_systems.positions:
  - [4, 5]
  - [5, 1]
# Positions of wormholes to battleground.
wormholes.positions:
  - [1, 6]
  - [2, 1]
  - [6, 3]
  - [5, 7]
# Positions of mini battlegrounds.
mini_battlegrounds.positions:
  - [1, 2]
  - [6, 5]
  - [7, 0]
  
convoy.time: <%= 1.hour %> / speed
# Speed modifier for convoy ships.
convoy.speed_modifier: 6
# - [count_from, count_to, type, flank]
#
# count numbers are inclusive.
convoy.units:
  - [0, 10, Dirac, 0]
  - [1, 10, Dirac, 1]
  - [0, 5, Thor, 0]
  - [0, 10, Thor, 1]
  - [0, 4, Demosis, 0]
  - [0, 2, Demosis, 1]