---
######
# Galaxy configuration
######

# Diameter of starting zone
zone.diameter: 8
# Players per zone.
zone.players: 20

# How long initial shield lasts on players home solar system?
player.shield_duration: <%= 2.weeks %>
# When should the inactivity check be scheduled for?
player.inactivity_check: <%= 1.week %>
# How much points must player have to be considered active?
player.inactivity_check.points: 15000
# How recent should last player login be if he doesn't have enough points?
player.inactivity_check.last_login_in: <%= 3.days %>

# All positions are relative to zone and not overridable in other sets!

# Positions of expansion systems.
expansion_systems.positions:
  - [2, 4]
# Positions of resource systems.
resource_systems.positions:
  - [4, 5]
  - [5, 1]
# Positions of wormholes to battleground.
wormholes.positions:
  - [1, 6]
  - [2, 1]
  - [6, 3]
  - [5, 7]