---
######
# Galaxy configuration
######


# There can't be other homeworlds in this radius
zone.diameter: 6

# Expansions per homeworld
expansion_systems.number: 2
# Resource systems per homeworld
resource_systems.number: 1