---

# Maximum number of active simulateneous offers for player.
offers.max: 15

# Minimal amount of resource you are able to offer.
offer.min_amount: 500

# Float percentage that we allow user submitted rate to vary from average market
# value.
average.offset: 0.10

# How much of the offer person should buy so that seller would get notified?
buy.notification.threshold: 0.03

### 
# Seed values for market values.
# 
# Seed value is: [from_amount, to_rate]
###
average.seed.0.1: [53289, 3.67]   # metal to energy
average.seed.0.2: [53289, 0.19]   # metal to zetium
average.seed.0.3: [20000, 0.1]    # metal to creds
average.seed.1.0: [195648, 0.27]  # energy to metal
average.seed.1.2: [195648, 0.05]  # energy to zetium
average.seed.1.3: [40000, 0.05]   # energy to creds
average.seed.2.0: [10310, 5.17]   # zetium to metal
average.seed.2.1: [10310, 18.98]  # zetium to energy
average.seed.2.3: [10000, 0.8]    # zetium to creds
average.seed.3.0: [1000, 10.0]    # creds to metal
average.seed.3.1: [1000, 20.0]    # creds to energy
average.seed.3.2: [1000, 1.25]    # creds to zetium

# Resource ranges for generated system offers.
bot.resources.range.0: [3750, 7500]         # metal range
bot.resources.range.1: [10000, 20000]       # energy range
bot.resources.range.2: [750, 1500]         # zetium range
# Cooldown range for when system offer is totally bought out.
bot.resources.cooldown: [<%= 10.minutes %> / speed, <%= 30.minutes %> / speed]
