---

# Maximum number of active simultaneous offers for player.
offers.max: 15

# Minimal amount of resource you are able to offer.
offer.min_amount: 500

# Float percentage that we allow user submitted rate to vary from average market
# value.
avg_rate.offset: 0.30
# If avg_rate - offset% is X, but market has entries with to_rate <= X, then
# allow player to add value that is X - this_offset.
avg_rate.min_price.offset: 0.001

# How much of the offer person should buy so that seller would get notified?
buy.notification.threshold: 0.03

### 
# Seed values for market values.
# 
# Seed value is: [from_amount, to_rate]
###
average.seed.0.1: [50000, 3.0]    # metal to energy
average.seed.0.2: [50000, 0.5]    # metal to zetium
average.seed.0.3: [10000, 0.2]    # metal to creds
average.seed.1.0: [150000, 0.333] # energy to metal
average.seed.1.2: [150000, 0.166] # energy to zetium
average.seed.1.3: [30000, 0.0666] # energy to creds
average.seed.2.0: [25000, 2.0]    # zetium to metal
average.seed.2.1: [25000, 6.0]    # zetium to energy
average.seed.2.3: [8500, 0.4]     # zetium to creds
average.seed.3.0: [10000, 5.0]    # creds to metal
average.seed.3.1: [10000, 15.0]   # creds to energy
average.seed.3.2: [10000, 2.5]    # creds to zetium

# Resource ranges for generated system offers.
bot.resources.range.0: [3750, 7500]         # metal range
bot.resources.range.1: [10000, 20000]       # energy range
bot.resources.range.2: [750, 1500]          # zetium range
# Selected amount of resources is multiplied by [1, day / day_divider].max
# when creating system offer. This ensures amount of resources stay relevant
# through course of the game.
bot.resources.day_divider: 3.0
# Cooldown range for when system offer is totally bought out.
bot.resources.cooldown: [<%= 10.minutes %> / speed, <%= 30.minutes %> / speed]
