---
######
# Planet configuration
######

# Planet name validation properties
validation.name.length.min: 3
validation.name.length.max: 12

# Max area restriction: width + height should not be more than this number.
# This is a limitation for Flash client.
area.max: 83

# Area size range. Area is width + height.
area: [50, 65]

# Width/height division in area. If set to 30, height will be 30% of width.
area.proportion: [45, 55]

# Mapping: terrain_type: [variations]
terrain.types:
  # Earth type
  0: [0, 1, 2, 3]
  # Desert type
  1: [4, 5, 6]
  # Mud type
  2: [7, 8]

# Percentage of nonblocking folliage that should cover the map
folliage.area: [20, 30]

# This type of folliage only has number N of items in the map. One item cannot
# be closer to others of this type than spacing_radius tiles.
folliage.type.1.count: [3, 4]
folliage.type.1.spacing_radius: 7
# This type of folliage only has N% of items in the map. One item cannot
# be closer to others of this type than spacing_radius tiles.
folliage.type.2.percentage: [0, 10]
folliage.type.2.spacing_radius: 4

# Files belonging to each type.
# http://nebula44.com/mantis/view.php?id=169
### Type 1
# Earth planets
folliage.type.1.variations.0: [12, 13]
# Desert planets
folliage.type.1.variations.1: [12, 13]
# Mud planets
folliage.type.1.variations.2: [9, 8]
### Type 2
# Earth planets
folliage.type.2.variations.0: [10, 11]
# Desert planets
folliage.type.2.variations.1: [10, 11]
# Mud planets
folliage.type.2.variations.2: [10, 13]


# Homeworld map
# . is regular
# S is sand
# J is junkyard
# N is noxrium
# T is titan
# W is water
# - is void
#
# O is ore (2x2)
# % is geothermal (2x2)
# $ is zetium (2x2)
# 6 is folliage (6x6)
# ^ is folliage (6x2)
# 4 is folliage (4x6)
# @ is folliage (4x4)
# ! is folliage (4x3)
# 3 is folliage (3x3)
# # is folliage (3x4)
#
# These tiles must be laid in such fashion:
#
# . - - . . .
# . O - - - .
# . . . $ - .
# . . . . . .
#
# You can put buildings by writing building letter near to a tile like this:
#
# Buildings:
#   M - mothership (8x6)
#   V - Vulcan tower (2x2)
#   S - Screamer tower (2x2)
#   T - Thunder tower (2x2)
#   X - NPC metal eXtractor (2x2)
#   G - NPC Geothermal extractor (2x2)
#   Z - NPC Zetium extractor (2x2)
#   P - NPC solar Plant (2x2)
#   H - NPC communications Hub (3x2)
#   E - NPC tEmple (3x3)
#   C - NPC exCavation site (4x4)
#   R - NPC Research center (4x4)
#   U - NPC jUmpgate (5x5)
#   A - NPC hAll (gives victory points) (2x2)
#   I - NPC Infantry factory (3x3)
#   N - NPC taNks factory (4x4)
#   F - NPC space Factory (4x5)
#
# . . . . . .
# . .-.-. . .
# . .V.-. . .
# . . . . . .
# First tile is of given type, and other one's are void.
homeworld.map:
- "S-S-S S . . . . . . . . . .-.-. S ----S S S S S S S S . .-.-"
- "SPS-S SPS-. . - - - - - - .P.-. . $Z--. S-.-- - - . S . SP.-"
- "S S S .-S-S . - - - - - - . . . . . . . .P.-- - - S-S-. S S "
- "S S . . S S . - - - - - - . .-.-. . . . . . - - - .P.-. S T "
- ". . . . . . . - - - - - - . .P.-. . . . . . # - - . . . S T "
- ". . . J . J . - - - - - - . . . . . - - . . . . . . . T T-T-"
- ". . J J J J . 6 - - - - - . . . . . O - . .-.-.-. . T T TPT-"
- ". J J J J J . . . . . . . . . . . . . . . .H.-.-. . T S S S "
- ". J J J J . . . . . - - . . . . . . . . . . . .-.-. . S S S "
- ". J J J . . . . . . O - . . . . . . . . . . . .P.-. . .-.-S "
- ". J . . . T T . . . . . . . . . . . . . . . . . . . . .PS-S "
- ". . . . T T T T T . . . . . . . . . . . . . .-.-.-. . S S S "
- ". - - - - - - - T .-.-.-.-.-.-.-.-.-.-.-.-. .H.-.-. . S-S-S "
- ". ^ - - - - - - T .T.-.V.-.T.-.S.-.T.-.V.-. . . . . . .PS-S "
- ". . S . . . . . . .-.-.-.-.-.-.-.-.-.-.-.-. . . . . . . S . "
- "S . S S . . . . . .V.-.-.-.-.-.-.-.-.-.T.-. .-.-. . . . . . "
- "S S S S S . . . . .-.-.-.-.-.-.-.-.-.-.-.-. .P.-. . ----. . "
- "S S S S S . . . . .S.-.-.-.-.-.-.-.-.-.S.-. . . . . $Z--. . "
- "S S . S . . T . . .-.-.-.-.-.-.-.-.-.-.-.-. . . J . . . . J "
- "S . S S . . . T T .T.-.M.-.-.-.-.-.-.-.V.-. .-.-J J J J J J "
- "S - - - - T T T T .-.-.-.-.-.-.-.-.-.-.-.-. .PJ-J J-J-J-J J "
- "S - - - - T T . . .V.-.S.-.T.-.V.-.S.-.T.-. . . J JHJ-J-J J "
- "S - - - - . T . . . - - - . . . . . . . . . . . J J J J J J "
- "S - - - - . . . . . - - - .-.-. . . . . . .-.-. . . J J J . "
- "S - - - - . . . . . 3 - - .P.-. . . N N N .P.-. ----. J ----"
- "S 4 - - - . .-.-.-N N . . N N N-.-N N-N-N N . . OX--. . OX--"
- "S S S . . . .H.-.-N N N . . N NPN-N NPN-N N . N . . . . . . "
- ". . S ----. . . . . N N N-N-N N N N N N N N N-N-N . .-.-.-. "
- "----. OX--. . .-.-.-. N NPN-N N-N-N N-N-N N NPN-N . .H.-.-. "
- "OX--. . . . . .H.-.-N N N N N NPN-N NPN-N N N N . . . . . . "
#

battleground.map.0:
- ". . . . . . . . . . . . . . . . . . . . . "
- ". . . . . . . . . . . . . . .-.-.-.-. . . "
- ". . .-.-.-.-. - - - - . . . .-.-.-.-. . . "
- ". . .-.-.-.-. - - - - . . . .-.-.-.-. . . "
- ". . .-.-.-.-. ! - - - . . . .-.-.-.-. . . "
- ". . .N.-.-.-. . . . . . . . .F.-.-.-. . . "
- ". . . . . . . . . . . . . . . . . . . . . "
- "- - - . . . . . . . .-.-. . - - - - . . . "
- "- - - . . . . . . . .A.-. . - - - - . . . "
- "3 - - . . . .-.-.-. . . . . # - - - . . . "
- ". . . . . . .-.-.-. . . . . . . . . . . . "
- ". . - - - . .I.-.-. . . . . - - - - - - . "
- ". . - - - . . . . . . . . . - - - - - - . "
- ". . 3 - - . . - - - - . . . - - - - - - . "
- ". . . . . . . - - - - . . . - - - - - - . "
- "- - - - - - . - - - - . . . - - - - - - . "
- "^ - - - - - . @ - - - . . . 6 - - - - - . "

battleground.map.1:
- ". . . . . . . . . . - - - . . . . . . . . . . "
- "- - - . . .-.-.-. . - - - . - - - - - - . . . "
- "- - - . . .-.-.-. . 3 - - . ^ - - - - - . . . "
- "- - - . . .I.-.-. . . . . . . . . . . . . . . "
- "# - - . . . . . . . .-.-. .-.-.-.-. . . . . . "
- ". . . . . . . . . . .A.-. .-.-.-.-. . - - - - "
- ". . .-.-.-.-. . . . . . . .-.-.-.-. . - - - - "
- ". . .-.-.-.-. - - - . . . .-.-.-.-. . ! - - - "
- ". . .-.-.-.-. - - - . . . .F.-.-.-. . . . . . "
- ". . .N.-.-.-. 3 - - . . . . . . . . . . . . . "
- ". . . . . . . . . . . - - - - - - . - - - - . "
- ". - - - - - - . . . . ^ - - - - - . - - - - . "
- ". ^ - - - - - . . . . . . . . . . . ! - - - . "

battleground.map.2:
- ". . . . . . . . . . .-.-.-.-. "
- ". . . . . - - - - . .-.-.-.-. "
- ". .-.-.-. - - - - . .-.-.-.-. "
- ". .-.-.-. ! - - - . .N.-.-.-. "
- ". .I.-.-. . . . . . . . . . . "
- ". . . . . . .-.-. - - - - - - "
- ". . . . . . .A.-. ^ - - - - - "
- ". . . . . . . . . . . . . . . "
- ". . .-.-.-.-. . . - - - - - - "
- ". . .-.-.-.-. . . - - - - - - "
- ". . .-.-.-.-. . . - - - - - - "
- ". . .-.-.-.-. . . - - - - - - "
- ". . .F.-.-.-. . . - - - - - - "
- ". . . . . . . . . 6 - - - - - "
- ". . . . . . . . . . . . . . . "

### Block tile ranges.
### These are piece based, meaning that 3 will mean not 3% but 3 tiles

# Resource tile ranges
tiles.ore: [4, 8]
tiles.geothermal: [0, 2]
tiles.zetium: [2, 4]
# Folliage tile ranges
tiles.f6x6: [0, 1]
tiles.f6x2: [0, 1]
tiles.f4x6: [0, 1]
tiles.f4x4: [0, 1]
tiles.f4x3: [0, 1]
tiles.f3x4: [0, 1]
tiles.f3x3: [0, 1]
#

### Area tile ranges.
### These are proportion based (excluding resource tiles).
### Isles is isle count of that specific type in terrain.
tiles.regular: [160, 200]
tiles.titan: [15, 25]
tiles.titan.isles: [3, 5]
tiles.junkyard: [30, 50]
tiles.junkyard.isles: [3, 5]
tiles.sand: [10, 50]
tiles.sand.isles: [3, 5]
tiles.noxrium: [20, 45]
tiles.noxrium.isles: [3, 5]
#

### NPC building chances
###
### All chances are percentage between 0 and 100.


# This defines chance that resource tile will have NPC unit on it.
npc.tiles.ore.chance: 45
npc.tiles.geothermal.chance: 95
npc.tiles.zetium.chance: 90

# This defines chances for other npc buildings in this planet
# [chance, building type]
npc.building.chances:
  - [80, npc_jumpgate]
  - [50, npc_jumpgate]
  - [50, npc_jumpgate]
  - [90, npc_research_center]
  - [60, npc_excavation_site]
  - [60, npc_communications_hub]
  - [20, npc_research_center]
  - [40, npc_excavation_site]
  - [70, npc_temple]
  - [90, npc_communications_hub]
  - [70, npc_solar_plant]
  - [70, npc_solar_plant]
  - [100, npc_solar_plant]
  - [100, npc_solar_plant]

# Npc extractor importances. We are allowing these to be tweaked manually.
# All other NPC buildings have their importance calculated by their area: 
# importance = width * height
npc.building.metal_extractor.importance: 5
npc.building.geothermal_plant.importance: 16
npc.building.zetium_extractor.importance: 10

# Defines what units are in buildings. More important unit is more units it will
# have inside.
#
# [min importance, chance, unit type, flank]

# Building importances:
# min: 4
# comm hub: 6
# temple: 9
# excavation site, research center: 16
# jumpgate: 25
npc.building.units:
  - [25, 100, gnawer, 0]
  - [25, 50, gnawer, 0]
  - [16, 100, gnawer, 0]
  - [16, 40, gnawer, 0]
  - [16, 50, spudder, 0]
  - [16, 20, spudder, 0]
  - [16, 60, spudder, 1]
  - [10, 10, gnawer, 0]
  - [10, 40, spudder, 0]
  - [9, 30, spudder, 1]
  - [9, 100, spudder, 0]
  - [8, 90, glancer, 1]
  - [8, 40, gnat, 0]
  - [8, 20, gnat, 1]
  - [6, 70, gnat, 0]
  - [6, 50, gnat, 0]
  - [6, 100, glancer, 1]
  - [6, 100, glancer, 1]
  - [5, 80, glancer, 1]
  - [5, 40, glancer, 1]
  - [5, 20, glancer, 1]
  - [5, 10, glancer, 1]
  - [4, 100, gnat, 0]
  - [4, 100, gnat, 0]
  - [4, 100, gnat, 1]
  - [4, 40, gnat, 0]
  - [4, 40, gnat, 0]
  - [4, 40, gnat, 1]
  - [4, 40, gnat, 1]
  - [4, 20, gnat, 0]
  - [4, 20, gnat, 1]