---
# Map explanation:
# . is regular
# _ is sand
# # is junkyard
# / is noxrium
# ^ is titan
# - is void
#
# O is ore (2x2)
# % is geothermal (2x2)
# $ is zetium (2x2)
#
# 1 is folliage (2x4)
# 2 is folliage (2x3)
# 5 is folliage (3x2)
# * is folliage (3x4)
# 3 is folliage (3x3)
# ! is folliage (4x3)
# @ is folliage (4x4)
# 4 is folliage (4x6)
# ~ is folliage (6x2)
# 6 is folliage (6x6)
#
# These tiles must be laid in such fashion:
#
# . - - . . .
# . O - - - .
# . . . $ - .
# . . . . . .
#
# You can put buildings by writing building letter near to a tile like this:
#
# Buildings:
#   m - mothership (8x6)
#   h - headquarters (4x5)
#   b - barracks (3x3)
#   x - MEX T2 (2x2)
#   c - Collector T2 (2x4)
#   z - ZEX T2 (2x2)
#   a - NPC hAll (gives victory points) (2x2)
#   i - NPC Infantry factory (3x3)
#   n - NPC taNks factory (4x4)
#   f - NPC space Factory (4x5)
#
# Barracks:
# . .-.-.-. .
# . .-.-.-. .
# . .b.-.-. .
# . . . . . .
#
# Buildings with garrisoned units:
#   X - NPC metal eXtractor (2x2)
#   G - NPC Geothermal extractor (2x2)
#   Z - NPC Zetium extractor (2x2)
#
#   P - NPC solar Plant (2x2)
#   H - NPC communications Hub (3x2)
#   E - NPC tEmple (3x3)
#   C - NPC exCavation site (4x4)
#   R - NPC Research center (4x4)
#   U - NPC jUmpgate (5x5)
#
# NPC solar plant with level 3 garrisoned units:
# . . . . . .
# . .-.-. . .
# . .P.3. . .
# . . . . . .
#
# First tile is of given type, second one is level (0 to 9) and other one's are
# void.
homeworld:
  - terrain: <%= Terrain::EARTH %>
    name: Terra
    # More weight means more probability this map will be picked.
    weight: 1000
    map:
      - "----. . . . .-/-/ .-/-/ . . . / / . . /-/-. . . . .-.-. .-. .-.-.-. .-.-.-.-. "
      - "$Z-2. .-.-. .P/2/ /P/2/ /-/-/ /-/-/ . /P/2. / / . .P.4.P.4. .-.-.-. .P.4.P.4. "
      - ". . . .P.1. . / / . / / /P/2/ .P/2/ . / / . /-/-. .-.-. .-. .E.0.-. .-.-.-.-. "
      - "----- . . .-.-/ / . / / / / / . / / .-/-/ . /P/2. .P.4.P.4. . . . . .P.4.P.4. "
      - "----- . . .P.1/ / .-.-. /-/-/ . / / /P/1. . / / . ------------------------. . "
      - "----- . . . . . / /P/1/ /P/1. / / . . / . / /-.-. ~-----------~-----------. . "
      - "*---- .-.-. .-/-. . / / . . / / /-/-/ /-/-/ .P.1. . . . . .-.-.-. . . . . . . "
      - "# . . .P.0. /P/0/ / /-/-. .-/-/ /P/0/ .P/0/ . . . .-.-.-^ ^H^4^-. .-.-.-. .-.-"
      - "#-#-# . . . . / . . /P/0. .P/0/ / / . . / / .-.-. ^H^4^-^ ^ . ^ . .H.4.-. .P.2"
      - "#P.3# # # . . ^ ^ . ^ ^ ------------. .-/-/ .P.0^ ^ ^ . . . . ^ ^ ------------"
      - "# # # #-#-# . ^ ^ ^ ^ ^ ^-----------. .P.0. . . ^ . --------. ^ ^ ------------"
      - "# # # #P#3# # . . . . . . / . . . . . . --------^ ^ --------. . ^ ------------"
      - "#-#-# # # # # . ----. . . / / . . . . . --------. . --------. ^-^-------------"
      - "#P#3# # # #-#-. OX-1. . . . . / / / . . !-------. . @-------. ^P^2------------"
      - "# # # # # #P#3# . . . . / /-. /-. /-/ . . . . . . . . . . . ^ ^ . 6-----------"
      - ". #-.-# # . . . . ------/ /-. /-. /-/ ----------------. . . ^ ^ ^ ^ . . . . . "
      - "# #P#3. # . ----. ------/ /-. /-/ /-. ----------------. ------. ^-^-^ . . . . "
      - ". . . . . . OX-0. 3-----. / . . / / . ----------------. ------. .P.2^ .-.-.-. "
      - ".-.-. . . . . . . . . . . /-. /-/ /-/ ----------------. ------. ^ ^ ^ .H.4.-. "
      - ".P.1. ----. . --------. . /-. /-/ /-. ----------------. *-----. ^-^-. . . . . "
      - "_ . . $Z-0. . --------. . /-/ /-/ /-. -m--------------. . . . . .P^2^ ^-^-. . "
      - "_ _ . . . . . --------. . / / / . / / . . . . # . . # # . . . . . . ^ ^P^2. . "
      - "_ _ _ . . . . --------. . . /-. ----/ . _ _ # # # # # # . --------. . ^ . . . "
      - ".-_-.-_ _ _ . --------. . / /-. O---/ ----_ # # # # # . . --------. .-^-. . . "
      - "_H_0_-_ . _ _ 4-------. . / /-. / / / O---_ # # # # # . . !-------. ^P^2. .-.-"
      - "_ _ _ _ . _ _ _ _ . . _ . . / / / _ _ _ _ _ # # # # # . . . . . . . ^ ^ . .P.2"
      - "_ _-_-_-. _-_-_-_ . _ _ . . _ . _ ------_ _ ------------. ^-^-^ ^ . ^ .-.-. . "
      - "_ _H_1_-_ _H_0_-_ _ . _ _ _ _ . _ ------. _ ~-----------. ^P^2. ^ ^ ^ .P.2. . "
      - ". . _ . . _ . . . _ . . _ _ . _ . 3-----_ _ _ . ^ ^ . . . . ^ . ^-^-. . . . . "
      - "_-_-_-_ . _ _ _ _ _-.-_-_ . . _ _ _ _ _ _ ----. ^-^-^ ^ ^ ^-^-. .P#3# # . . . "
      - "_H_2_-_ _ _-_-_-_ _H_0.-_ . . _ . ----. _ OX-1. .P.2. ^ ^ .P.2# # # . # #-.-. "
      - "_ _ _ _ . _H_1_-_ . _ . . _ _ _ . OX-0. _ _ . . . . .-.-. . . # . . . . #P.3. "
      - "_ _-_-_-_ _ _ _ _ .-_-_-_ _ . . _ . . . . _ . ----. .P#3# # # # # # # . # . . "
      - ". .H.2_-. .-.-_-. _H.1_-_ . _-.-.-_ . . _ . . $Z-1. . # # # #-#-# . #-.-# . . "
      - "_ _ _ _ . _H_2_-_ _ _ . _ _ .H_0.-_ . _ . _ _ . . . . #-#-# #P#3# . .P#3# # . "
      - "_-_-_-_ _ _ _ _ _ .-_-.-. _ _ _ _ . _-_-_-. _ _ . # # #P#3# # # # . . # . # . "
      - "_H_3_-_ _-_-_-_ _ .H_2_-_ _-.-_-_ _ _H.0.-_ _-_-_-. . # # # #-#-# #-#-# . #-#-"
      - "_ _ _ _ .H_3_-_ _ . _ _ . _H.1_-_ . _ _ . . _H.0.-_ . # . . #P#3# .P#3# . .P#3"

expansion:
  - terrain: <%= Terrain::MUD %>
    name: Nova
    weight: 1000
    map:
      - "/ / . /-/-/ /-/-/ /-/-/ / . . . . . . #-#-#-# . . . ----. . # #-#-#-#-# # . . "
      - "/-/-/ /P/5. /P/5. /P/5. . ------.-.-# #-#-#-. ----. %G-0# . # #-#-#-#-# . # . "
      - "/P/5. / / / / / / / / / . ------.P.6. #E#2#-. $Z-5. . . . # # #-#-#-#-# # ----"
      - "/ / . / /-.-/ /-.-/ /-.-. 3-----. . . . # . # . # . .-#-.-.-# #R#5#-#-# . %G-0"
      - ". /-/-. /P.5/ .P.5/ .P.5. . . . . . ----# #-.-.-# . #-.-.-.-# # # # # # # . . "
      - "/ /P.5/ / / / / . / . . .-.-_-_ . . OX-5. .H#7#-# # #-#-#-#-# # # # #-#-.-.-# "
      - "/ / / / /-.-/ / /-.-.-. .-.-_-_ . . . . # . # # # # #R#4#-.-# .-#-. #-.-.-#-# "
      - "/-/-. / /P/4/ / .H.5.-. _E_0.-. .-.-.-.-. #-#-#-#-# # # . . # .P.8. #-#-.-#-. "
      - "/P/4/ / / . / / . . _ . . _ . _ .-.-.-.-. .-#-#-#-# # # . . # . # . .R#3#-#-# "
      - ". / . . / . / . .-_-_-_ .-.-.-. .-#-#-#-# #-#-#-#-# # # # # # # # . # # # # # "
      - "/ ----. . /-.-. .H_4.-_ _H.4.-. #R#1.-#-. .R#2#-#-# # # # ----. #-#-. #-#-#-# "
      - ". OX-3/ / /P.4. . . . . _ # # # # . . . . . # . # . # . . $Z-4. .P#7. #-#-#-# "
      - "/ / / / / . . . ----. . _ _ _-#-.-.-_ _ --------. .-#-.-. . . . . # . #E#1#-# "
      - "/ ------------. $Z-3. . . # #-#-#-.-. _ --------. .-.-.-. . _ .-.-.-. # . # . "
      - ". ------------. . . . . . # #-#-#-#-# . --------. .E_0_-. . _ _H.6.-# # . # # "
      - ". ------------. . ^ ^ . . . #R#0#-.-# . --------. . . _ _ . . _ _ . . . ----. "
      - ". ------------. ^ ^ ^ ^ . . # . # . . . --------. .-_-_-. .-.-.-. .-.-. OX-4. "
      - ". ------------^ ^ --------. . . ----. . 4-------. .H.5.-. .H_5_-_ .P_6_ . . . "
      - ". 6-----------^ . --------. ^ . OX-2. . . . . . . . . . . _ _ . _ . . _ . .-.-"
      - ". . . ^ ^ ^ . ^ . !-------^ ^ ^ . . ^ ^ ^ . . . . .-.-.-. _ ------------. .P.6"
      - ". ^ ^ ^ ^ ^ ^ ^ ^ ^ . . . ^ ------------^ ^ ----. .H.4.-. _ ~-----------. _ _ "
      - ". ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ . ^ ^ ~-----------^ . OX-2. . . . . . . . . . . . . _ . "
      - "^ ^ . . . . . . . ^ ^ ^ ^ . . . ^ ^ ^ . ^ ^ . ^ ^ ^ ^ ^ . .-.-.-. .-_-. .-.-. "
      - "^ ^ . . ------. . ^ ^ . ^ ^ . . ^ . ^ ^ . ^ ^ ^ ^ . . ^ . ^H.4.-. _P_5. .P.5/ "
      - ". . . . ------. . . . . ^ ^ ^ ^ . . . ^ . ^ . --------^ ^ ^ . . _ _ . . / . / "
      - ". ----. -b----. ----. . . . . ^ ^ ^ . ^ ^ . . --------. ^ . . .-.-. .-/-. /-.-"
      - ". Ox--. . . . . ----. . ----. . ^ ^ ^ ^ ^ . . --------^ ^-.-. /P.5/ /P.5/ .P/5"
      - ". . . . . ----. ----. . $z--. . . . . ^ ^ ^ ^ @-------^ ^P.4/ . / . / . / . / "
      - ". . . . . Ox--. -c--. . . . . . . . . . . ^ . . ^ ^ ^ ^ . . / . / / / / / / / "
      - "--------. . . . . . . . . . . . # # # # . ^ ^ ^ ^ . ^ . / /-/-. /-.-/ . .-.-/ "
      - "--------. . ----. ----. ----. # # . # # . . ^ ^ . ------. .P/4/ .P/4/ / .P/5/ "
      - "--------. . ----. ----. ----. # # # # . # . ^ ^ . ------. / . . / . / / / / / "
      - "--------. . ----. ----. ----. # # # # # # . ^ ^ ^ ------. ----. /-/-/ / . /-/-"
      - "-h------. . -c--. -c--. -c--. # # # # # # . ^ ^ . *-----. OX-3. /P.4/ / / /P/4"

# In these maps such signature
#
# . . . . .
# . .-.-. .
# . .-.-. .
# . . . . .
#
# Marks a spot where a player can place its turret.
battleground:
  - terrain: <%= Terrain::EARTH %>
    name: Gramen
    weight: 1000
    # 12 turrets
    map:
      - ". . . ^ ^ ^ ^ ^ . .-.-. ------------. "
      - ". . . . . . ^-^-^ .-.-. ~-----------. "
      - ". --------. ^-^-^ ^ ^ . . ^ ^ ^ ^ . . "
      - ". --------. . . ^ ----. . ^ . --------"
      - ". --------. ^-^-^ ----. ^-^-. --------"
      - ". -n------^ ^-^-^ 2---. ^-^-. --------"
      - ". . . . . ^ . . ^ ^ ^ ^ ^ . . @-------"
      - "^-^-^ ^-^-^ ^-^-^ ----. ^-^-. . . . . "
      - "^-^-^ ^-^-. ^-^-^ -a--. ^-^-^ ^ . . . "
      - ". ^ . . . . ^ . ^ . . . ^ . . --------"
      - "^ ^ ------. ^-^-. ----. ^-^-. --------"
      - ". . ------. ^-^-. ----. ^-^-. --------"
      - ". . -i----. . ^ . ----. . ^ ^ --------"
      - ". . . . . . ^-^-. 1---. ^-^-. -f------"
      - ". . . . . . ^-^-. . . . ^-^-^ ^ . . . "
  - terrain: <%= Terrain::DESERT %>
    name: Inculta
    weight: 1000
    # 10 turrets
    map:
      - "^ ^-^-^ ^-^-. ^-^-. --------. "
      - ". ^-^-. ^-^-. ^-^-. --------. "
      - "^ ^ ^ . . ^ . . ^ . --------^ "
      - "----^ ------. ^-^-. --------^ "
      - "----^ ------. ^-^-^ -f------^ "
      - "2---^ -i----. . . ^ ^ . . . ^ "
      - ". . ^ ^ ^ ^ . ----. ^-^-^ ^-^-"
      - ". ------. ^ . -a--. ^-^-. ^-^-"
      - ". 5-----. ^ . . . . . . . ^ . "
      - "^ ^ ^ ^ ^ ^-^-. ------. ^-^-. "
      - "--------. ^-^-. ------. ^-^-. "
      - "--------. . ^ . ------. . ^ . "
      - "--------. ^-^-. *-----. ^-^-. "
      - "-n------^ ^-^-. . ^ ^ ^ ^-^-. "
      - ". . . ^ ^ . ^ ^ ^ ^ . . . . . "
  - terrain: <%= Terrain::MUD %>
    name: Limus
    weight: 1000
    # 8 turrets
    map:
      - ". . . . . . ^-^-^ ----^ ^-^-^ ^-^-. "
      - ". --------. ^-^-^ ----^ ^-^-^ ^-^-. "
      - ". --------. . . . ----. . ^ . . . . "
      - ". --------. ^-^-. 1---. . ^ --------"
      - "^ @-------^ ^-^-. . . . . ^ --------"
      - "^ ^ . . . ^ . . . --------^ --------"
      - "^-^-. ^-^-^ ----^ --------^ @-------"
      - "^-^-. ^-^-. -a--^ --------^ ^ . . . "
      - ". ^ ^ ^ . . . ^ ^ -n------. --------"
      - ". --------. ^-^-. . . . . . --------"
      - ". --------. ^-^-^ ------. . --------"
      - ". --------. . . ^ ------. . --------"
      - ". --------. ^-^-^ -i----. . --------"
      - ". -f------. ^-^-^ ^ ^ . . . 4-------"

free_systems:
  - terrain: <%= Terrain::EARTH %>
    name: Gramen
    weight: 1000
    # 12 turrets
    map:
      - ". . . ^ ^ ^ ^ ^ . .-.-. ------------. "
      - ". . . . . . ^-^-^ .-.-. ~-----------. "
      - ". --------. ^-^-^ ^ ^ . . ^ ^ ^ ^ . . "
      - ". --------. . . ^ ----. . ^ . --------"
      - ". --------. ^-^-^ ----. ^-^-. --------"
      - ". -n------^ ^-^-^ 2---. ^-^-. --------"
      - ". . . . . ^ . . ^ ^ ^ ^ ^ . . @-------"
      - "^-^-^ ^-^-^ ^-^-^ ----. ^-^-. . . . . "
      - "^-^-^ ^-^-. ^-^-^ -a--. ^-^-^ ^ . . . "
      - ". ^ . . . . ^ . ^ . . . ^ . . --------"
      - "^ ^ ------. ^-^-. ----. ^-^-. --------"
      - ". . ------. ^-^-. ----. ^-^-. --------"
      - ". . -i----. . ^ . ----. . ^ ^ --------"
      - ". . . . . . ^-^-. 1---. ^-^-. -f------"
      - ". . . . . . ^-^-. . . . ^-^-^ ^ . . . "
  - terrain: <%= Terrain::DESERT %>
    name: Inculta
    weight: 1000
    # 10 turrets
    map:
      - "^ ^-^-^ ^-^-. ^-^-. --------. "
      - ". ^-^-. ^-^-. ^-^-. --------. "
      - "^ ^ ^ . . ^ . . ^ . --------^ "
      - "----^ ------. ^-^-. --------^ "
      - "----^ ------. ^-^-^ -f------^ "
      - "2---^ -i----. . . ^ ^ . . . ^ "
      - ". . ^ ^ ^ ^ . ----. ^-^-^ ^-^-"
      - ". ------. ^ . -a--. ^-^-. ^-^-"
      - ". 5-----. ^ . . . . . . . ^ . "
      - "^ ^ ^ ^ ^ ^-^-. ------. ^-^-. "
      - "--------. ^-^-. ------. ^-^-. "
      - "--------. . ^ . ------. . ^ . "
      - "--------. ^-^-. *-----. ^-^-. "
      - "-n------^ ^-^-. . ^ ^ ^ ^-^-. "
      - ". . . ^ ^ . ^ ^ ^ ^ . . . . . "
  - terrain: <%= Terrain::MUD %>
    name: Limus
    weight: 1000
    # 8 turrets
    map:
      - ". . . . . . ^-^-^ ----^ ^-^-^ ^-^-. "
      - ". --------. ^-^-^ ----^ ^-^-^ ^-^-. "
      - ". --------. . . . ----. . ^ . . . . "
      - ". --------. ^-^-. 1---. . ^ --------"
      - "^ @-------^ ^-^-. . . . . ^ --------"
      - "^ ^ . . . ^ . . . --------^ --------"
      - "^-^-. ^-^-^ ----^ --------^ @-------"
      - "^-^-. ^-^-. -a--^ --------^ ^ . . . "
      - ". ^ ^ ^ . . . ^ ^ -n------. --------"
      - ". --------. ^-^-. . . . . . --------"
      - ". --------. ^-^-^ ------. . --------"
      - ". --------. . . ^ ------. . --------"
      - ". --------. ^-^-^ -i----. . --------"
      - ". -f------. ^-^-^ ^ ^ . . . 4-------"