---
######
# Planet configuration
######

# Planet name validation properties
validation.name.length.min: 3
validation.name.length.max: 12

# Mapping: terrain_type: [variations]
terrain.types:
  # Earth type
  0: [0, 1, 2, 3]
  # Desert type
  1: [4, 5, 6]
  # Mud type
  2: [7, 8]

# Percentage of nonblocking folliage that should cover the map
folliage.area: [20, 30]

# This type of folliage only has number N of items in the map. One item cannot
# be closer to others of this type than spacing_radius tiles.
folliage.type.1.count: [3, 4]
folliage.type.1.spacing_radius: 7
# This type of folliage only has N% of items in the map. One item cannot
# be closer to others of this type than spacing_radius tiles.
folliage.type.2.percentage: [0, 10]
folliage.type.2.spacing_radius: 4

# Files belonging to each type.
# http://nebula44.com/mantis/view.php?id=169
### Type 1
# Earth planets
folliage.type.1.variations.0: [12, 13]
# Desert planets
folliage.type.1.variations.1: [12, 13]
# Mud planets
folliage.type.1.variations.2: [9, 8]
### Type 2
# Earth planets
folliage.type.2.variations.0: [10, 11]
# Desert planets
folliage.type.2.variations.1: [10, 11]
# Mud planets
folliage.type.2.variations.2: [10, 13]