---
# How many ranking points player should get for battle round.
# xp_with_dead - all XP player earned, including units that are dead at
# the end of the round.
# xp - XP player earned, excluding dead units.
points.war: ((xp_with_dead - xp) / 2 + xp) * 2.7