---
######
# Solar System configuration
######

# Maximum number of orbits where planets and asteroids can be. This is also
# maximum number of planets available, if you try to create more planets than
# there are orbits, generator will fail!
orbit.count: 3

# How much time does it take to go between points in orbit. 1 is normal hop
# time, 2 is double time, 0.5 is half time.
links.orbit.weight: (0.3 * position) + 0.4
# How much time does it take to go between orbits.
links.parent.weight: (0.3 * position) + 0.7
# How much time does it take to land to the planet. Does not support formulas!
links.planet.weight: 1.2

# Number of planets in homeworld ss. Not a range! Does not include homeworld
# planet!
homeworld.planet.count: 1
# Number of planets in expansion ss
expansion.planet.count: [2, 3]
# Number of planets in resources ss
resources.planet.count: [1, 2]
# Fixed positions and terrains for planets in battleground solar system.
# [position, angle]
# Must have spaces between numbers!
battleground.planet.positions: [[0, 270], [1, 45], [2, 210]]

# Number of asteroids in homeworld ss. Not a range!
homeworld.asteroid.count: 5
# Number of asteroids in expansion ss
expansion.asteroid.count: [3, 8]
# Number of asteroids in resources ss
resources.asteroid.count: [1, 4]
# Battlegrounds do not have asteroids.

# Number of rich asteroids in homeworld ss. Not a range!
homeworld.rich_asteroid.count: 0
# Number of rich asteroids in expansion ss
expansion.rich_asteroid.count: [2, 9]
# Number of rich asteroids in resources ss
resources.rich_asteroid.count: [5, 7]
# Battlegrounds do not have asteroids.

# Number of jumpgates in homeworld ss. Not a range!
homeworld.jumpgate.count: 1
# Number of jumpgates in expansion ss
expansion.jumpgate.count: [1, 2]
# Number of jumpgates in resources ss
resources.jumpgate.count: [2, 4]
# Fixed positions of jumpgates in battleground.
# Must have spaces between numbers!
battleground.jumpgate.positions: [[3, 22], [3, 134], [3, 270]]
