---
######
# Solar System configuration
######

# Maximum number of orbits where planets and asteroids can be. This is also
# maximum number of planets available, if you try to create more planets than
# there are orbits, generator will fail!
orbit.count: 3

# How much time does it take to go between points in orbit. 1 is normal hop
# time, 2 is double time, 0.5 is half time.
links.orbit.weight: (0.3 * position) + 0.4
# How much time does it take to go between orbits.
links.parent.weight: (0.3 * position) + 0.7
# How much time does it take to land to the planet. Does not support formulas!
links.planet.weight: 1.1

# How much time should jump from/to regular solar system take?
regular.jump.multiplier: 1.5
# How much time should jump from/to global battleground take?
battleground.jump.multiplier: 4

### Unit spawning
# Available strategies:
# - outer_circle: Spawn only in last circle of solar system, avoiding jumpgates.
# - random: Spawn anywhere in the solar system.

# Time range for spawning.
spawn.regular.delay: [<%= 12.hours %> / speed, <%= 24.hours %> / speed]
# Maximum number of spots occupied by NPC units in SS.
spawn.regular.max_spots: 5
# - [count_from, count_to, type, flank]
#
# count numbers are inclusive.
spawn.regular.units:
  - [2, 6, Dirac, 0]
  - [2, 8, Dirac, 1]
  - [1, 3, Thor, 0]
  - [2, 5, Thor, 1]
  - [0, 2, Demosis, 0]
  - [0, 2, Demosis, 1]
# Spawning strategy to use
spawn.regular.strategy: outer_circle

# Time range for spawning.
spawn.mini_battleground.delay: [<%= 6.hours %> / speed, <%= 24.hours %> / speed]
# Maximum number of spots occupied by NPC units in SS.
spawn.mini_battleground.max_spots: 3
# - [count_from, count_to, type, flank]
#
# count numbers are inclusive.
spawn.mini_battleground.units:
  - [5, 10, Dirac, 0]
  - [5, 20, Dirac, 1]
  - [5, 10, Thor, 0]
  - [5, 15, Thor, 1]
  - [1, 8, Demosis, 0]
  - [0, 10, Demosis, 1]
# Spawning strategy to use
spawn.mini_battleground.strategy: random

# Time range for spawning.
spawn.battleground.delay: [<%= 12.hours %> / speed, <%= 36.hours %> / speed]
# Maximum number of spots occupied by NPC units in SS.
spawn.battleground.max_spots: 1
# - [count_from, count_to, type, flank]
#
# count numbers are inclusive.
spawn.battleground.units:
  - [1, 1, BossShip, 0]
# Spawning strategy to use
spawn.battleground.strategy: outer_circle

