---
######
# Solar system object configuration
######

# Graphical size range of ss object (in percentage of main picture)
size: [25, 60]

# One step of asteroid rate values. Step 0.1 and range [1, 2] would mean 1, 1.1,
# 1.2, 1.3, 1.4, ..., 2
asteroid.rate_step: 0.1

# Asteroid resource ranges
asteroid.metal_rate: [1, 3]
rich_asteroid.metal_rate: [2, 6]
asteroid.energy_rate: [1, 3]
rich_asteroid.energy_rate: [2, 6]
asteroid.zetium_rate: [1, 3]
rich_asteroid.zetium_rate: [2, 6]

# Asteroid wreckage spawn rate ranges.
#
# 15 asteroids average, 3 hrs avg spawn time, 1 mule full capacity.
asteroid.wreckage.metal.spawn: [35, 105]
asteroid.wreckage.energy.spawn: [105, 315]
asteroid.wreckage.zetium.spawn: [18, 53]
asteroid.wreckage.time.spawn: [<%= 2.hours %>, <%= 4.hours %>]
# After player registers when to register first cooldown on asteroids in his
# solar system?
asteroid.wreckage.time.first: <%= 1.week %>

### Orbit units configuration. Not overridable.

# [type, range, flank]
#
# Where:
# range can be either Fixnum or [Fixnum, Fixnum]
# and flank can be either Fixnum or [Fixnum, Fixnum, ...]
regular.orbit.planet.units:
  - [demosis, [0, 6], 0]
  - [thor, [4, 10], [0, 1]]
  - [dirac, [6, 14], [0, 1]]
regular.orbit.asteroid.units:
  - [demosis, [0, 1], 0]
  - [thor, [2, 8], [0, 1]]
  - [dirac, [4, 10], [0, 1]]
regular.orbit.rich_asteroid.units:
  - [demosis, [1, 4], 0]
  - [thor, [2, 12], [0, 1]]
  - [dirac, [8, 16], [0, 1]]
regular.orbit.jumpgate.units:
  - [demosis, [2, 4], 0]
  - [thor, [6, 14], [0, 1]]
  - [dirac, [10, 16], [0, 1]]

homeworld.orbit.planet.units:
  - [dirac, 8, 0]
homeworld.orbit.asteroid.units:
  - [thor, 2, 0]
  - [dirac, 6, 1]
homeworld.orbit.rich_asteroid.units:
  - [thor, 4, 0]
  - [dirac, 12, 1]
homeworld.orbit.jumpgate.units:
  - [demosis, 2, 0]
  - [thor, 6, 0]
  - [dirac, 16, 1]

battleground.orbit.planet.units:
  - [demosis, [4, 10], [0, 1]]
  - [thor, [6, 20], [0, 1]]
  - [dirac, [10, 25], [0, 1]]
battleground.orbit.asteroid.units: []
battleground.orbit.rich_asteroid.units: []
battleground.orbit.jumpgate.units: []
