---
######
# Solar system object configuration
######

# Graphical size range of ss object (in percentage of main picture)
size: [25, 60]

# One step of asteroid rate values. Step 0.1 and range [1, 2] would mean 1, 1.1,
# 1.2, 1.3, 1.4, ..., 2
asteroid.rate_step: 0.1

# Asteroid resource ranges
asteroid.metal_rate: [1, 3]
rich_asteroid.metal_rate: [2, 6]
asteroid.energy_rate: [1, 3]
rich_asteroid.energy_rate: [2, 6]
asteroid.zetium_rate: [1, 3]
rich_asteroid.zetium_rate: [2, 6]

# Asteroid wreckage spawn rate ranges.
#
# 15 asteroids average, x * 3 hrs avg spawn time, 0,15 mule capacity.
<% mult = 36; cap = 0.15 %>

asteroid.wreckage.metal.spawn: [<%= mult * cap * 36 %>, <%= mult * cap * 104 %>]
asteroid.wreckage.energy.spawn: [<%= mult * cap * 104 %>, <%= mult * cap * 320 %>]
asteroid.wreckage.zetium.spawn: [<%= mult * cap * 18 %>, <%= mult * cap * 54 %>]
asteroid.wreckage.time.spawn: [<%= (mult * 2).hours %> / speed, <%= (mult * 4).hours %> / speed]
# After player registers when to register first cooldown on asteroids in his
# solar system?
asteroid.wreckage.time.first: <%= 3.days %> / speed

# Maximum values of each resource that can be on asteroid. Spawning will get
# slower when reaching these values
asteroid.wreckage.metal.spawn.max: 45000
asteroid.wreckage.energy.spawn.max: 90000
asteroid.wreckage.zetium.spawn.max: 15000

### Planet units configuration. Not overridable.
# This is needed so that people cannot take planets with only space units.

regular.planet.units:
  - [gnawer, [1, 2], 0]
  - [gnawer, [0, 1], 1]
  - [spudder, [2, 5], [0, 1]]
  - [glancer, [2, 5], 1]
  - [gnat, [5, 8], [0, 1]]
battleground.planet.units:
  - [gnawer, [2, 4], 0]
  - [gnawer, [0, 2], 1]
  - [spudder, [5, 10], [0, 1]]
  - [glancer, [5, 10], 1]
  - [gnat, [10, 15], [0, 1]]

### Pulsar/Battleground boss spawn configuration.

# Time range for spawning.
spawn.mini_battleground.delay: [<%= 12.hours %> / speed, <%= 48.hours %> / speed]
# - [count_from, count_to, type, flank]
# count_from and count_to are formulas with:
# - counter: which time spawn is being done in this SSO.
#
# count numbers are inclusive.
spawn.mini_battleground.units:
  - [20 + 1 * counter / 4, 30 + 4 * counter / 2, Gnat, 0]
  - [10 + 1 * counter / 3, 25 + 1 * counter / 3, Gnat, 1]
  - [5 + 1 * counter / 2, 15 + 3 * counter / 5, Glancer, 1]
  - [10 + 1 * counter / 4, 25 + 3 * counter / 5, Spudder, 1]
  - [8 + 1 * counter / 3, 24 + 2 * counter / 4, Gnawer, 0]
  - [1, 1 + counter / 20, Worg, 1]

spawn.battleground.delay: [<%= 24.hours %> / speed, <%= 60.hours %> / speed]
spawn.battleground.units:
  - [20 + 1 * counter / 4, 30 + 4 * counter / 2, Gnat, 0]
  - [10 + 1 * counter / 3, 25 + 1 * counter / 3, Gnat, 1]
  - [5 + 1 * counter / 2, 15 + 3 * counter / 5, Glancer, 1]
  - [10 + 1 * counter / 4, 25 + 3 * counter / 5, Spudder, 1]
  - [8 + 1 * counter / 3, 24 + 2 * counter / 4, Gnawer, 0]
  - [1, 3 + counter / 5, Worg, 1]