---
######
# Solar system object configuration
######

# Graphical size range of ss object (in percentage of main picture)
size: [25, 60]

# One step of asteroid rate values. Step 0.1 and range [1, 2] would mean 1, 1.1,
# 1.2, 1.3, 1.4, ..., 2
asteroid.rate_step: 0.1

# Asteroid resource ranges
asteroid.metal_rate: [1, 3]
rich_asteroid.metal_rate: [2, 6]
asteroid.energy_rate: [1, 3]
rich_asteroid.energy_rate: [2, 6]
asteroid.zetium_rate: [1, 3]
rich_asteroid.zetium_rate: [2, 6]

# Asteroid wreckage spawn rate ranges.
#
# 15 asteroids average, x * 3 hrs avg spawn time, 0,15 mule capacity.
<% mult = 36; cap = 0.15 %>

asteroid.wreckage.metal.spawn: [<%= mult * cap * 36 %>, <%= mult * cap * 104 %>]
asteroid.wreckage.energy.spawn: [<%= mult * cap * 104 %>, <%= mult * cap * 320 %>]
asteroid.wreckage.zetium.spawn: [<%= mult * cap * 18 %>, <%= mult * cap * 54 %>]
asteroid.wreckage.time.spawn: [<%= (mult * 2).hours %> / speed, <%= (mult * 4).hours %> / speed]
# After player registers when to register first cooldown on asteroids in his
# solar system?
asteroid.wreckage.time.first: <%= 3.days %> / speed

# Maximum values of each resource that can be on asteroid. Spawning will get
# slower when reaching these values
asteroid.wreckage.metal.spawn.max: 45000
asteroid.wreckage.energy.spawn.max: 90000
asteroid.wreckage.zetium.spawn.max: 15000

### Planet units configuration. Not overridable.
# This is needed so that people cannot take planets with only space units.

regular.planet.units:
  - [gnawer, [1, 2], 0]
  - [gnawer, [0, 1], 1]
  - [spudder, [2, 5], [0, 1]]
  - [glancer, [2, 5], 1]
  - [gnat, [5, 8], [0, 1]]
battleground.planet.units:
  - [gnawer, [2, 4], 0]
  - [gnawer, [0, 2], 1]
  - [spudder, [5, 10], [0, 1]]
  - [glancer, [5, 10], 1]
  - [gnat, [10, 15], [0, 1]]

### Orbit units configuration. Not overridable.

<%
  dirac_flanks = "[0, 1, 1]"
  thor_flanks = "[0, 0, 0, 1, 1]"
  demosis_flanks = "[0, 0, 0, 0, 1]"
%>

# [type, range, flank]
#
# Where:
# range can be either Fixnum or [Fixnum, Fixnum]
# and flank can be either Fixnum or [Fixnum, Fixnum, ...]
regular.orbit.planet.units:
  - [dirac, [37, 43], <%= dirac_flanks %>]
  - [thor, [27, 33], <%= thor_flanks %>]
  - [demosis, [8, 10], <%= demosis_flanks %>]
regular.orbit.asteroid.units:
  - [dirac, [33, 40], <%= dirac_flanks %>]
  - [thor, [23, 30], <%= thor_flanks %>]
  - [demosis, [7, 9], <%= demosis_flanks %>]
regular.orbit.jumpgate.units:
  - [dirac, [30, 37], <%= dirac_flanks %>]
  - [thor, [20, 27], <%= thor_flanks %>]
  - [demosis, [6, 8], <%= demosis_flanks %>]

battleground.orbit.planet.units:
  - [dirac, [53, 60], <%= dirac_flanks %>]
  - [thor, [43, 50], <%= thor_flanks %>]
  - [demosis, [13, 15], <%= demosis_flanks %>]
  - [boss_ship, [0, 1], 0]
battleground.orbit.asteroid.units:
  - [dirac, [50, 57], <%= dirac_flanks %>]
  - [thor, [40, 47], <%= thor_flanks %>]
  - [demosis, [12, 14], <%= demosis_flanks %>]
battleground.orbit.jumpgate.units:
  - [dirac, [47, 53], <%= dirac_flanks %>]
  - [thor, [37, 43], <%= thor_flanks %>]
  - [demosis, [11, 13], <%= demosis_flanks %>]
