---
######
# Solar system object configuration
######

# Graphical size range of ss object (in percentage of main picture)
size: [25, 60]

# One step of asteroid rate values. Step 0.1 and range [1, 2] would mean 1, 1.1,
# 1.2, 1.3, 1.4, ..., 2
asteroid.rate_step: 0.1

# Asteroid resource ranges
asteroid.metal_rate: [1, 3]
rich_asteroid.metal_rate: [2, 6]
asteroid.energy_rate: [1, 3]
rich_asteroid.energy_rate: [2, 6]
asteroid.zetium_rate: [1, 3]
rich_asteroid.zetium_rate: [2, 6]

# Asteroid wreckage spawn rate ranges.
#
# 15 asteroids average, x * 3 hrs avg spawn time, 0,15 mule capacity.
<% mult = 36; cap = 0.15 %>

asteroid.wreckage.metal.spawn: [<%= mult * cap * 36 %>, <%= mult * cap * 104 %>]
asteroid.wreckage.energy.spawn: [<%= mult * cap * 104 %>, <%= mult * cap * 320 %>]
asteroid.wreckage.zetium.spawn: [<%= mult * cap * 18 %>, <%= mult * cap * 54 %>]
asteroid.wreckage.time.spawn: [<%= (mult * 2).hours %> / speed, <%= (mult * 4).hours %> / speed]
# After player registers when to register first cooldown on asteroids in his
# solar system?
asteroid.wreckage.time.first: <%= 3.days %> / speed

# Maximum values of each resource that can be on asteroid. Spawning will get
# slower when reaching these values
asteroid.wreckage.metal.spawn.max: 18000
asteroid.wreckage.energy.spawn.max: 45000
asteroid.wreckage.zetium.spawn.max: 8000

### Planet units configuration. Not overridable.
# This is needed so that people cannot take planets with only space units.

regular.planet.units:
  - [gnawer, [1, 2], 0]
  - [gnawer, [0, 1], 1]
  - [spudder, [2, 5], [0, 1]]
  - [glancer, [2, 5], 1]
  - [gnat, [5, 8], [0, 1]]
battleground.planet.units:
  - [gnawer, [2, 4], 0]
  - [gnawer, [0, 2], 1]
  - [spudder, [5, 10], [0, 1]]
  - [glancer, [5, 10], 1]
  - [gnat, [10, 15], [0, 1]]
homeworld.planet.units: []

### Orbit units configuration. Not overridable.

# [type, range, flank]
#
# Where:
# range can be either Fixnum or [Fixnum, Fixnum]
# and flank can be either Fixnum or [Fixnum, Fixnum, ...]
regular.orbit.planet.units:
  - [demosis, [0, 3], 0]
  - [thor, [2, 5], [0, 1]]
  - [dirac, [3, 7], [0, 1]]
regular.orbit.asteroid.units:
  - [demosis, [0, 1], 0]
  - [thor, [1, 4], [0, 1]]
  - [dirac, [2, 5], [0, 1]]
regular.orbit.rich_asteroid.units:
  - [demosis, [0, 2], 0]
  - [thor, [1, 6], [0, 1]]
  - [dirac, [4, 8], [0, 1]]
regular.orbit.jumpgate.units:
  - [demosis, [1, 2], 0]
  - [thor, [3, 7], [0, 1]]
  - [dirac, [5, 8], [0, 1]]

homeworld.orbit.planet.units:
  - [dirac, 4, 0]
homeworld.orbit.asteroid.units:
  - [thor, 1, 0]
  - [dirac, 4, 1]
homeworld.orbit.rich_asteroid.units:
  - [thor, 3, 0]
  - [dirac, 6, 1]
homeworld.orbit.jumpgate.units:
  - [demosis, 1, 0]
  - [thor, 3, 0]
  - [dirac, 8, 1]

battleground.orbit.planet.units:
  - [demosis, [2, 8], [0, 1]]
  - [thor, [3, 12], [0, 1]]
  - [dirac, [5, 20], [0, 1]]
battleground.orbit.asteroid.units: []
battleground.orbit.rich_asteroid.units: []
battleground.orbit.jumpgate.units: []

  
