---
# Technologies configuration file.

# Multiplier for resource need when overtime is forced
speed_up.resources.mod: 2
# Multiplier for time reduction when overtime is forced
speed_up.time.mod: 2

### fiery_melters config ###

fiery_melters.max_level: 10
fiery_melters.upgrade_time: (90 * 2 ** level - scientists * 3) / speed
fiery_melters.metal.cost: 50 * 2 ** level
fiery_melters.energy.cost: 235 * 2 ** level
fiery_melters.zetium.cost: 0
fiery_melters.coords: [0, 0]
fiery_melters.scientists.min: 10
fiery_melters.mod.metal.generate: 12 * level
fiery_melters.mod.metal.store: 12 * level

### superconductor_technology config ###

superconductor_technology.max_level: 10
superconductor_technology.upgrade_time: (90 * 2 ** level - scientists * 3) / speed
superconductor_technology.metal.cost: 300 * 2 ** level
superconductor_technology.energy.cost: 60 * 2 ** level
superconductor_technology.zetium.cost: 0
superconductor_technology.coords: [1, 0]
superconductor_technology.scientists.min: 10
superconductor_technology.mod.energy.generate: 10 * level
superconductor_technology.mod.energy.store: 12*  level

### zetium_extraction config ###

zetium_extraction.metal.cost: 140 
zetium_extraction.energy.cost: 160 
zetium_extraction.max_level: 1
zetium_extraction.upgrade_time: (60 - (scientists - 10) * 3) / speed
zetium_extraction.coords: [2, 2]
zetium_extraction.scientists.min: 10

### powdered_zetium config ###

powdered_zetium.max_level: 10
powdered_zetium.upgrade_time: (90 * level - scientists * 3) / speed
powdered_zetium.metal.cost: 300 * 2 ** level
powdered_zetium.energy.cost: 350 * 2 ** level
powdered_zetium.zetium.cost: 50 * 2 ** level
powdered_zetium.coords: [3, 2]
powdered_zetium.requirement.zetium_extraction.level: 1
powdered_zetium.scientists.min: 10
powdered_zetium.mod.zetium.generate: 10 * level
powdered_zetium.mod.zetium.store: 12 * level

seeker.max_level: 3
seeker.upgrade_time: (400 - scientists * 3) / speed
seeker.metal.cost: 350
seeker.energy.cost: 200
seeker.zetium.cost: 400
seeker.coords: [9, 0]
seeker.scientists.min: 10
seeker.mod.armor: 5 * (level-1)
seeker.mod.damage: 5 * (level-1)
seeker.applies_to:
  - unit/seeker

shocker.max_level: 3
shocker.upgrade_time: (600 - scientists * 3) / speed
shocker.metal.cost: 100
shocker.energy.cost: 350
shocker.zetium.cost: 0
shocker.coords: [8, 0]
shocker.scientists.min: 10
shocker.mod.armor: 5 * (level-1)
shocker.mod.damage: 5 * (level-1)
shocker.applies_to:
  - unit/shocker

wind_panel.max_level: 1
wind_panel.upgrade_time: (900 - scientists * 3) / speed
wind_panel.metal.cost: 1500
wind_panel.energy.cost: 600
wind_panel.zetium.cost: 200
wind_panel.coords: [0, 1]
wind_panel.requirement.superconductor_technology.level: 3
wind_panel.scientists.min: 20

geothermal_plant.max_level: 1
geothermal_plant.upgrade_time: (900 - scientists * 3) / speed
geothermal_plant.metal.cost: 1500
geothermal_plant.energy.cost: 800
geothermal_plant.zetium.cost: 900
geothermal_plant.coords: [1, 1]
geothermal_plant.requirement.superconductor_technology.level: 5
geothermal_plant.scientists.min: 10

#spy.max_level: 1
#spy.upgrade_time: (90 - scientists * 3) / speed
#spy.metal.cost: 100
#spy.energy.cost: 200
#spy.zetium.cost: 400
#spy.coords: [6, 0]
#spy.scientists.min: 10
#
#saboteur.max_level: 1
#saboteur.upgrade_time: (90 - scientists * 3) / speed
#saboteur.metal.cost: 100
#saboteur.energy.cost: 200
#saboteur.zetium.cost: 400
#saboteur.coords: [7, 1]
#saboteur.requirement.spy.level: 1
#saboteur.scientists.min: 10
#
#tactical_reconnaissance.max_level: 1
#tactical_reconnaissance.upgrade_time: (90 - scientists * 3) / speed
#tactical_reconnaissance.metal.cost: 100
#tactical_reconnaissance.energy.cost: 200
#tactical_reconnaissance.zetium.cost: 400
#tactical_reconnaissance.coords: [6, 1]
#tactical_reconnaissance.requirement.spy.level: 1
#tactical_reconnaissance.scientists.min: 10
#
#sattelite_hacking.max_level: 1
#sattelite_hacking.upgrade_time: (90 - scientists * 3) / speed
#sattelite_hacking.metal.cost: 100
#sattelite_hacking.energy.cost: 200
#sattelite_hacking.zetium.cost: 400
#sattelite_hacking.coords: [6, 2]
#sattelite_hacking.requirement.tactical_reconnaissance.level: 1
#sattelite_hacking.scientists.min: 10
#
#camouflage_suits.max_level: 1
#camouflage_suits.upgrade_time: (90 - scientists * 3) / speed
#camouflage_suits.metal.cost: 100
#camouflage_suits.energy.cost: 200
#camouflage_suits.zetium.cost: 400
#camouflage_suits.coords: [7, 2]
#camouflage_suits.requirement.saboteur.level: 1
#camouflage_suits.scientists.min: 10
#
#r14_charges.max_level: 1
#r14_charges.upgrade_time: (90 - scientists * 3) / speed
#r14_charges.metal.cost: 100
#r14_charges.energy.cost: 200
#r14_charges.zetium.cost: 400
#r14_charges.coords: [8, 2]
#r14_charges.requirement.saboteur.level: 1
#r14_charges.scientists.min: 10

metabolic_chargers.max_level: 10
metabolic_chargers.upgrade_time: (90 - scientists * 3) / speed
metabolic_chargers.metal.cost: 80 * 2 ** level
metabolic_chargers.energy.cost: 130 * 2 ** level
metabolic_chargers.zetium.cost: 60 * 2 ** level
metabolic_chargers.coords: [8, 1]
metabolic_chargers.requirement.high_velocity_charges.invert: true
metabolic_chargers.scientists.min: 10
metabolic_chargers.mod.armor: 5* level
metabolic_chargers.applies_to:
  - unit/trooper
  - unit/shocker
  - unit/seeker
  - unit/spy
  - unit/saboteur

high_velocity_charges.max_level: 4
high_velocity_charges.upgrade_time: (90 - scientists * 3) / speed
high_velocity_charges.metal.cost: 130 * 2 ** level
high_velocity_charges.energy.cost: 80 * 2 ** level
high_velocity_charges.zetium.cost: 80 * 2 ** level
high_velocity_charges.coords: [9, 1]
high_velocity_charges.requirement.metabolic_chargers.invert: true
high_velocity_charges.scientists.min: 10 
high_velocity_charges.mod.damage: 12 * level
high_velocity_charges.applies_to:
  - unit/trooper
  - unit/shocker
  - unit/seeker
  - unit/spy
  - unit/saboteur

#resource_transporter.max_level: 1
#resource_transporter.upgrade_time: (90 - scientists * 3) / speed
#resource_transporter.metal.cost: 100
#resource_transporter.energy.cost: 200
#resource_transporter.zetium.cost: 400
#resource_transporter.coords: [1, 5]
#resource_transporter.requirement.spaceport.level: 1
#resource_transporter.scientists.min: 10

radar.max_level: 1
radar.upgrade_time: (90 - scientists * 3) / speed
radar.metal.cost: 700
radar.energy.cost: 900
radar.zetium.cost: 400
radar.coords: [1, 2]
radar.scientists.min: 30

### vulcan config ###

# Coordinates in technology tree
vulcan.coords: [3, 0]

# Upgrade properties
vulcan.max_level: 1
vulcan.upgrade_time: (<%= 1.hour %> - scientists * <%= 1.minute %>) / speed
vulcan.metal.cost: 1500
vulcan.energy.cost: 2000
vulcan.zetium.cost: 600
# Minimum amount of scientists needed
vulcan.scientists.min: 10

# Technological requirements
#vulcan.requirement.zetium_extraction.level: 1

### screamer config ###

# Coordinates in technology tree
screamer.coords: [4, 0]

# Upgrade properties
screamer.max_level: 1
screamer.upgrade_time: (<%= 1.hour %> - scientists * <%= 1.minute %>) / speed
screamer.metal.cost: 2500
screamer.energy.cost: 3000
screamer.zetium.cost: 400
# Minimum amount of scientists needed
screamer.scientists.min: 10

# Technological requirements
#screamer.requirement.zetium_extraction.level: 1

### thunder config ###

# Coordinates in technology tree
thunder.coords: [5, 0]

# Upgrade properties
thunder.max_level: 1
thunder.upgrade_time: (<%= 1.hour %> - scientists * <%= 1.minute %>) / speed
thunder.metal.cost: 1000
thunder.energy.cost: 3000
thunder.zetium.cost: 900
# Minimum amount of scientists needed
thunder.scientists.min: 10

# Technological requirements
#thunder.requirement.zetium_extraction.level: 1

### space_factory config ###

# Coordinates in technology tree
space_factory.coords: [2, 3]

# Upgrade properties
space_factory.max_level: 1
space_factory.upgrade_time: (<%= 1.hour %> - scientists * <%= 1.minute %>) / speed
space_factory.metal.cost: 1200
space_factory.energy.cost: 400
space_factory.zetium.cost: 300
# Minimum amount of scientists needed
space_factory.scientists.min: 30

# Technological requirements
space_factory.requirement.zetium_extraction.level: 1

#### spaceport config ###
#
## Coordinates in technology tree
#spaceport.coords: [0, 4]
#
## Upgrade properties
#spaceport.max_level: 1
#spaceport.upgrade_time: (<%= 1.hour %> - scientists * <%= 1.minute %>) / speed
#spaceport.metal.cost: 400
#spaceport.energy.cost: 400
#spaceport.zetium.cost: 100
## Minimum amount of scientists needed
#spaceport.scientists.min: 10
#
## Technological requirements
#spaceport.requirement.space_factory.level: 1

### dart config ###

# Coordinates in technology tree
dart.coords: [1, 4]

# Upgrade properties
dart.max_level: 1
dart.upgrade_time: (<%= 1.hour %> - scientists * <%= 1.minute %>) / speed
dart.metal.cost: 800
dart.energy.cost: 200
dart.zetium.cost: 450
# Minimum amount of scientists needed
dart.scientists.min: 10

# Technological requirements
dart.requirement.space_factory.level: 1

### cyrix config ###

# Coordinates in technology tree
cyrix.coords: [2, 4]

# Upgrade properties
cyrix.max_level: 1
cyrix.upgrade_time: (<%= 1.hour %> - scientists * <%= 1.minute %>) / speed
cyrix.metal.cost: 2500
cyrix.energy.cost: 3000
cyrix.zetium.cost: 1500
# Minimum amount of scientists needed
cyrix.scientists.min: 30

# Technological requirements
cyrix.requirement.space_factory.level: 1

### avenger config ###

# Coordinates in technology tree
avenger.coords: [3, 4]

# Upgrade properties
avenger.max_level: 1
avenger.upgrade_time: (<%= 1.hour %> - scientists * <%= 1.minute %>) / speed
avenger.metal.cost: 1400
avenger.energy.cost: 1400
avenger.zetium.cost: 1000
# Minimum amount of scientists needed
avenger.scientists.min: 40

# Technological requirements
avenger.requirement.space_factory.level: 1

### rhyno config ###

# Coordinates in technology tree
rhyno.coords: [2, 5]

# Upgrade properties
rhyno.max_level: 1
rhyno.upgrade_time: (<%= 1.hour %> - scientists * <%= 1.minute %>) / speed
rhyno.metal.cost: 4000
rhyno.energy.cost: 4000
rhyno.zetium.cost: 2000
# Minimum amount of scientists needed
rhyno.scientists.min: 200

# Technological requirements
rhyno.requirement.cyrix.level: 1

### ground_factory config ###

# Coordinates in technology tree
ground_factory.coords: [7, 3]

# Upgrade properties
ground_factory.max_level: 1
ground_factory.upgrade_time: (<%= 1.hour %> - scientists * <%= 1.minute %>) / speed
ground_factory.metal.cost: 1300
ground_factory.energy.cost: 500
ground_factory.zetium.cost: 250
# Minimum amount of scientists needed
ground_factory.scientists.min: 15

### mdh config ###

# Coordinates in technology tree
mdh.coords: [6, 4]

# Upgrade properties
mdh.max_level: 1
mdh.upgrade_time: (<%= 1.hour %> - (scientists * <%= 1.minute %>)) / speed
mdh.metal.cost: 2000
mdh.energy.cost: 2000
mdh.zetium.cost: 700
# Minimum amount of scientists needed
mdh.scientists.min: 10

# Technological requirements
mdh.requirement.ground_factory.level: 1

### azure config ###

# Coordinates in technology tree
azure.coords: [7, 4]

# Upgrade properties
azure.max_level: 1
azure.upgrade_time: (<%= 1.hour %> - scientists * <%= 1.minute %>) / speed
azure.metal.cost: 1400
azure.energy.cost: 1600
azure.zetium.cost: 300
# Minimum amount of scientists needed
azure.scientists.min: 10

# Technological requirements
azure.requirement.ground_factory.level: 1
