---
# Plus 2 percent of armor for each titan tile
titan.mod.armor: 2
junkyard.mod.construction: 2
sand.mod.armor: -2
noxrium.mod.energy: 6

### Folliage exploration ###

# How much scientists we need?
exploration.scientists: 2 * width * height
# How much time will it take?
exploration.time: width * height * 40 / speed
# What chance we have to get something?
exploration.winning_chance: (width * height) ** 1.15
# Rewards if we get something. These are generated in
# config/initializers/exploration_rewards.rb
exploration.rewards.win.with_units.generator_config:
  # Number of variations
  number: 100
  # Level range for extractors (inclusive)
  level: [1, 8]
  # Time range for extractors (inclusive)
  time: [<%= 10.minutes %>, <%= 6.hours %>]
  # Possible unit types
  unit_types: ["gnat", "glancer", "spudder"]
  # Unit count range (inclusive)
  unit_count: [0, 2]
  # Unit HP % range (inclusive)
  unit_hp: [20, 70]
exploration.rewards.win.without_units.generator_config:
  # Number of variations
  number: 100
  # Level range for extractors (inclusive)
  level: [1, 8]
  # Time range for extractors (inclusive)
  time: [<%= 10.minutes %>, <%= 6.hours %>]
  # Possible unit types
  unit_types: []
  # Unit count range (inclusive)
  unit_count: [0, 0]
  # Unit HP % range (inclusive)
  unit_hp: [20, 70]
exploration.rewards.lose.with_units.generator_config:
  # Number of variations
  number: 100
  # Level range for extractors (inclusive)
  level: [1, 4]
  # Time range for extractors (inclusive)
  time: [<%= 1.minute %>, <%= 10.minutes %>]
  # Possible unit types
  unit_types: ["gnat"]
  # Unit count range (inclusive)
  unit_count: [0, 1]
  # Unit HP % range (inclusive)
  unit_hp: [5, 15]
exploration.rewards.lose.without_units.generator_config:
  # Number of variations
  number: 100
  # Level range for extractors (inclusive)
  level: [1, 4]
  # Time range for extractors (inclusive)
  time: [<%= 1.minute %>, <%= 10.minutes %>]
  # Possible unit types
  unit_types: []
  # Unit count range (inclusive)
  unit_count: [0, 0]
  # Unit HP % range (inclusive)
  unit_hp: [5, 15]
