#!/bin/bash
#
# Called by git-commit with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

update_assets() {
  src="$1"
  dst="$2"

  for dir in images icons; do
    dir="$src/$dir"

    # Skip non-existant directories
    if [ ! -d "$dir" ]; then
      continue
    fi

    for file in $(find "$dir" -type f); do
      basefile=${file/$src\//}

      srcfile="$file"
      dstfile="$dst/$basefile"

      if [ "$srcfile" -nt "$dstfile" ]; then
        echo mkdir -p "$dst/${basefile%/*}"
        cp -f "$srcfile" "$dstfile"
        git add "$dstfile"
      fi
    done
  done
}

update_assets_bidirectional() {
  update_assets "$1" "$2"
  update_assets "$2" "$1"
}

DIR="$(pwd)/flex"

update_assets_bidirectional "$DIR/bin-release/assets" "$DIR/src/assets"

exit 0
